### ISSUE TITLE
Custom widget on docs

### ISSUE THREAD

**Issue by mrsheldon** [DiscordBotList/issues#10]
#### Custom widget on docs isn't working

the example of the customize widget on the document isn't working

#### Applicable Links or Attachements

https://mrsheldon.me/captures/797030.png

#### Steps to Reproduce

1. go to https://discordbots.org/api/docs#widgets
2. scroll down

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment]
Looks like the bot we used as example has been deleted 😮

**Comment by tonkku107** [comment]
Fixed.
