### ISSUE TITLE
Search box on safari looks wacky 

### ISSUE THREAD

**Issue by Chew** [DiscordBotList/issues#100]
#### Expected Behavior

I expected the search box to look like the other browsers

#### Observed Behavior

Instead it looks shrunk

#### Applicable Links or Attachments

![Image of box](https://cdn.discordapp.com/attachments/134445052805120001/473531694536982544/unknown.png)

#### Steps to Reproduce

1. Open Discordbots.org on safari
2. tada

#### Web Browser and Version

Safari Version 11.0.1 (13604.3.5)

#### Operating System and Version

macOS High Sierra 10.13.1

#### Screen Resolution

1920x1080

#### Additional Information/Comments

It might be because safari sux

**Comment by Chew** [comment]
Is this fixed and no push released yet? Still broken for me

**Comment by tonkku107** [comment]
Clear cache and refresh

**Comment by Chew** [comment]
This still happens on https://top.gg/servers
