### ISSUE TITLE
Allow to filter bots by server count when going into a page/tag/all

### ISSUE THREAD

**Issue by GeoffreyWesthoff** [DiscordBotList/issues#11]
#### Suggestion

Allow to filter bots by server count when going into a page/tag/all

- Couldn't hurt
- Gives the user more choices

Not all bots implement voting rewards/locks but might still be worth the attention, I'm not saying this has to be the default, but it could be a worthwhile optional filter to add.

#### Applicable Links or Attachements

![Location for this button](http://i-got-banned-for-posting.an-invite.link/Ehtrou.png)

**Comment by melmsie** [comment]
+1

**Comment by tonkku107** [comment]
We haven't done this because we feel like it'll incentivize faking server count

**Comment by NovusTheory** [comment]
Because adding sorting by votes or allowing developers to fetch votes to give "rewards" doesn't incentivize a bad thing either? If you don't add stuff because you think it incentivizes faking or abuse then you'll just have to lock all the API's

**Comment by melmsie** [comment]
I'd also like to add that I'm decent at sniffing out fake guild counts. And
to get on the first page of top guild counts, it would be painfully obvious
if they were faking.

**Comment by Oliyy** [comment]
We are not planning to add this option anytime soon due to the abuse we suspect we will receive. We might revisit this down the line when and if discord allows querying server count through their API.
