### ISSUE TITLE
Remove the discord.gg requirement from the support invite.

### ISSUE THREAD

**Issue by Merlintor** [DiscordBotList/issues#113]
#### Suggestion

Make it possible to use a website url as a support invite. I have a website that redirects to the right invite url to make it easier for me to manage them. But I can't use that on dbl, because you require the invite to be a "discord.gg" url.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/33966852/43703411-051f1446-995d-11e8-9017-79c1083aab16.png)

**Comment by Chewsterchew** [comment]
I don't see a use for this, bot invite links sure, but the support link?

**Comment by fatchan** [comment]
It allows you to have your website redirect to the invite, so you can remove it and easily change it in the event of a raid, without having to change the support link on DBL (or other listing sites). Also you can have analytics to analyse the URL if you put some kind of referrer query string and find out where your invites are coming from.

**Comment by Chewsterchew** [comment]
Makes sense, but you can
1) revoke the invite on discord
2) see how many people used the invite...on discord

**Comment by fatchan** [comment]
Yes, but then you have to replace the invite link anywhere you posted it
bot lists, social media, info channels in the server, etc.
It makes sense to have a permanent link with interchangable invite behind it.

Plus its not about _how many_ times an invite used, its about the source. You can have yourwebsite.com/invite?source=<somewhere>
And track how many invite link clicks you get from each of those sources. Also helps determine rate of people who click the invite link and actually accept/join the server

**Comment by Merlintor** [comment]
I temporarily solved the problem by adding a small js script to my long description.
(Only possible if you are certified)

```
<script>
  var a = document.getElementById('support');
  a.href = "your invite link"
</script>
```

**Comment by tonkku107** [comment]
We're not going to remove the `discord.gg` requirement on support server invites.
