### ISSUE TITLE
Editing You'r Profile

### ISSUE THREAD

**Issue by TheTeaCup** [DiscordBotList/issues#117]
#### Expected Behavior

https://discordbots.org/me/edit When you edit, it should change

#### Observed Behavior

It does not change

#### Applicable Links or Attachments

![Profile](https://tea.wheres-my-ta.co/JKmTz.png)
![Edit](https://tea.wheres-my-ta.co/XBdch.png)

#### Steps to Reproduce

1. Open Discordbots.org
2. Login
3. Go to your profile
4. Click Edit
5. Submit and nothing changed for me

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

**Comment by TheTeaCup** [comment]
I fixed the issue by doing it twice

**Comment by TheTeaCup** [comment]
But one thing shouldnt you social media accounts show up?

**Comment by tonkku107** [comment]
Old user profiles are currently unsupported and some features have been disabled. A rewrite in the new design is coming soon.
