### ISSUE TITLE
Viewing Clyde's bot page returns a 500 error

### ISSUE THREAD

**Issue by zBlakee** [DiscordBotList/issues#12]
#### Expected Behavior

Being able to view Clyde's bot page as normal without seeing an error

#### Observed Behavior

Visiting Clyde's bot page on DBL will grant you with a 500 Internal Server Error 

#### Applicable Links or Attachements

Image of the error:
![Image of the error](https://please.zbot.me/zTGtjwQp.png)

What Clyde's bot page **should** look like:
![Clyde bot page image](https://please.zbot.me/J3kBhnMw.png)

[Clyde's bot page](https://discordbots.org/bot/1)

#### Steps to Reproduce

1. Navigate to https://discordbots.org/bot/1
2. You should receive an error

#### Web Browser and Version

Google Chrome -- Version 65.0.3325.181 (Official Build) (64-bit)

#### Operating System and Version

Windows 10 1709

#### Screen Resolution

1920x1080

#### Additional Information/Comments

The error seems to be caused by using `toLocaleString()` on `bot.monthlyVotes`, but Clyde is different to all the other bots in that Clyde has an invalid monthly votes value

**Comment by tonkku107** [comment]
Fixed
