### ISSUE TITLE
[DonateBot] Suggestions

### ISSUE THREAD

**Issue by PassiveModding** [DiscordBotList/issues#122]
#### Suggestion
-Subscriptions, custom time periods which are paid as a subscription, either automatically charge them or remove the role until they pay again.

Some things to keep in mind would be ensuring that subscriptions are revoked if the owner changes the time period or price, ie. 10/month would have to be revoked in order to ensure they dont end up getting charged like 10/day etc.

-More logging
Log changes to a log channel too, ie paypal email changed etc.

-Some checks to see if the server has changed ownership maybe

-Support for users / roles to manage settings
ie, add/edit roles

this could be done by setting user or role IDs in the settings panel and maybe some configuration in check boxes like edit roles, edit pricing, edit all, change paypal, etc.

**Comment by jczstudios** [comment]
Thank you for these suggestions, I don't quite understand what you mean by the ability for users / roles to manage settings. Do you mean Donate Bot settings? Subscriptions are a possibility for the future but right now, the alert channel is meant for the public and not just the server owner. You can also see some actions logged in the Audit Log by Donate Bot as well. Guild owners should be able to change ownership with no problems.

**Comment by PassiveModding** [comment]
For the users/roles I mean like having an admin or co-owner able to add new paid roles etc.

Also it'd be really neat to see subscriptions integrated. Thanks!

**Comment by jczstudios** [comment]
We've added subscriptions! A role for Donate Bot will be on our list for things to do in the future. Thank you for your suggestions!
