### ISSUE TITLE
/servers section: Server refuses to update.

### ISSUE THREAD

**Issue by Neeef** [DiscordBotList/issues#125]
#### Expected Behavior

I expected my server to update with new brief and detailed description.

#### Observed Behavior

Instead, the page loaded for ~2 minutes, then went back to the edit page with the info that I wanted to change. So pretty much it is not saving.

#### Applicable Links or Attachments

Console Error: https://i.imgur.com/S3vl2Rb.png
Server Page: https://discordbots.org/servers/466780741959680051

#### Steps to Reproduce

1. Open Discordbots.org
2. Go to your servers
3. Click edit on one of them
4. Change any info, descriptions, etc
5. Click Submit and wait.

#### Web Browser and Version

Google Chrome 64.0.3282.190 (Official Build) (64-bit)

#### Operating System and Version

Chrome OS Version 64.0.3282.190 (Official Build) (64-bit)
#### Screen Resolution

1920x1080 (laptop hooked up to monitor)

#### Additional Information/Comments

When you go to a different page with the console open, and the error is present the file in which is shown changes to something that looks like an ID on Discord.

**Comment by NotWeeb** [comment]
Fixed
