### ISSUE TITLE
"Top voted bots this month" suggested changes

### ISSUE THREAD

**Issue by unbelievable-pizza** [DiscordBotList/issues#13]
#### Suggestion

The same 6 bots are being shown at the top of the front page all month, and the next month will be mostly the same bots as well.
The only way to get in the top 6 is excessively vote "locking" your bot, or having a large enough bot you have enough users to reach the 14,000+ votes in a month.

##### Possible changes:
- Select 2 random bots from the first page of the 4 most searched tags (originally suggested by Melmsie#0001)
- Select 1 random bot from the first page of 6 random tags. Similar to above but this would allow top voted bots in less popular tags to make it on the front page. Maybe exclude the game tags from this.
- Select 6 random bots from the first 2 pages of top voted bots

#### Applicable Links or Attachements
None, although "Attachments" is spelt wrong in the template :p

**Comment by ohlookitsAugust** [comment]
+1 :3

**Comment by iDroid27210** [comment]
Yes make something about this.
Currently, I always see **the same** bots on the home page.
The only way to DiScOvEr bots (the main purpose of that kind of websites) is to browse through tags and that's something most of people doesn't want to do (they quickly want a bot so they choose one from the home page).

**Comment by AdityaTD** [comment]
I agree, maybe it should be balanced out by adding more random bots up top than top voted or however it can be balanced.

**Comment by Oliyy** [comment]
We are always aiming to make the front page diverse but also competitive. We are currently trying out different ways of structuring to add diversity, for example, we recently expanded the trending new bots section to 8. Giving new bots exposure. We are always trying to find a better balance for the front page.
