### ISSUE TITLE
Donate Bot web panel, server label bug

### ISSUE THREAD

**Issue by ThatTonybo** [DiscordBotList/issues#130]
#### Expected Behavior
When hovering over a server, the correct name should be displayed

#### Observed Behavior
The label only showed the first part of the server name

#### Applicable Links or Attachments
![image](https://user-images.githubusercontent.com/28176227/44315786-c269c380-a46a-11e8-86cc-d1c24e5627b8.png)
The real server name is `The "owo" Group :3`, but it only shows `The` as seen.

#### Steps to Reproduce
1. Open the donatebot.io web panel
2. Hover over a server that has quotes in the name

#### Web Browser and Version
Mozilla Firefox Quantum, Developers Edition, 62.0b17 (64bit) (aurora update channel)

#### Operating System and Version
Microsoft Windows 10 Home, 1803 [OS build 17134.228]

#### Screen Resolution
m1: 1366x768
m2: 1920x1080

#### Additional Information/Comments
Guessing that quotes aren't being parsed/replaced correctly. A bug I run into when making my own web panel. 😛

**Comment by Xignotic84** [comment]
Issue seems to have been resolved. If you're still having this issue feel free to reopen this issue.
