### ISSUE TITLE
Unable to add server

### ISSUE THREAD

**Issue by magiatrix** [DiscordBotList/issues#131]
#### Expected Behavior

I expected to find my server on my profile after adding the bot to the server I'm staff on.

#### Observed Behavior

Instead, nothing happened, the bot joined but my profile still didn't have the server on it.

#### Applicable Links or Attachments

![Image of my profile after adding bot to my server (its not the antibattyboy server)](https://i.imgur.com/6ff1T3r.png)
![Image of the bot in the server i want posted on the list, when i tried doing it the bot was online but then i found i can report this issue so in the picture the bot is offline but it was online when i tried posting it.](https://i.imgur.com/Ekx9WNW.png)

#### Steps to Reproduce

1. Added bot to server
2. Looked at profile

#### Web Browser and Version

Firefox Quantum Version 61.0.2 (64-bit)

#### Operating System and Version

Windows 10 Home 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

Because the bot went offline a few minutes after i kept on refreshing my profile, i think the bot was dead but it appeared online

**Comment by NotWeeb** [comment]
See #151 for updates | Discord Server List should now function as correctly and display online as expected
