### ISSUE TITLE
504 Gateway Error

### ISSUE THREAD

**Issue by MayorChano** [DiscordBotList/issues#135]
#### Expected Behavior

Edit should finish

#### Observed Behavior

504 gateway error

#### Applicable Links or Attachments

![screen shot 2018-08-26 at 10 29 05 pm](https://user-images.githubusercontent.com/41877062/44632744-40086480-a980-11e8-999f-9636168a5c8e.png)

#### Steps to Reproduce

1. Open Discordbots.org
2. Edit a bot

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment]
This was caused by a temporary server downtime

**Comment by MayorChano** [comment]
how much longer till its back?

**Comment by tonkku107** [comment]
Is it not back yet?
