### ISSUE TITLE
Changing the Name System  [Donatebot] 

### ISSUE THREAD

**Issue by berni1212** [DiscordBotList/issues#137]
Change the system with the Choose name for your donation because a lot of people missclick and then donate for a Random person make it that you have to confirm bevor you go to paypal where it sayes are you sure you wan't to donate for [Name]  if yes please press on okay if this name is wrong press on no and change it :)

**Comment by jczstudios** [comment]
We will be looking into the way that you select a user soon. A confirmation message might be a good idea. Thanks for the suggestion.

**Comment by jczstudios** [comment]
This will be updated shortly with the launch of our new checkout page.
