### ISSUE TITLE
Discord server list offline/Not working

### ISSUE THREAD

**Issue by BobbyMan227** [DiscordBotList/issues#144]
#### Expected Behavior

I expected the bot to go online so I can work on putting my server on Discordbots.org 

#### Observed Behavior

The bot is still offline. I have mentioned/tagged the bot both in my own server, and in the support server.

#### Applicable Links or Attachments
none

#### Steps to Reproduce

1. Make a discord server
2. go to Discordbots.org
3. invite Discord server list Bot to the server
4. tag/mention the bot

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

Is it just me, or is the bot down for some unforeseen reason?

**Comment by tonkku107** [comment]
https://discordapp.com/channels/417723229721853963/429358173099393048/489712326920896512

**Comment by BobbyMan227** [comment]
Thanks tonkku107 👍
