### ISSUE TITLE
Some users are missing from checkout page user list

### ISSUE THREAD

**Issue by crock** [DiscordBotList/issues#145]
#### Expected Behavior

I expect for all my members to find his own name in the list.

#### Observed Behavior

One of my members can't find his name in the list and I can't either. It doesn't come up when searched.

#### Steps to Reproduce

Not really sure how to re-produce this because it only happens with one person. The name does not have special characters either.

Leaving and re-joining has no effect.

**Comment by jczstudios** [comment]
This issue has been fixed! Thank you for reporting it.
