### ISSUE TITLE
Bug with profile

### ISSUE THREAD

**Issue by Perkaholic** [DiscordBotList/issues#151]
#### Expected Behavior

I expected to find my servers on my profile

#### Observed Behavior

My profile still only says "add server" even after I downloaded the bot to the server

#### Applicable Links or Attachments
https://cdn.discordapp.com/attachments/473646111966625812/493476184936546307/iii.PNG
https://cdn.discordapp.com/attachments/473646111966625812/493476265341354016/gggg.PNG

#### Steps to Reproduce

1. Go to my profile
2. See lack of servers

#### Web Browser and Version

Mozilla Firefox Version 62.0

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

**Comment by gloorgon** [comment]
you still have to add the server

**Comment by Oliyy** [comment]
You don't actually download bots for your server, the correct term is "add".
For the future ;)

**Comment by NotWeeb** [comment]
there seems to be a strange delay when adding a new server from fresh, try re-adding the server and/or editing your server on discord to force an update

**Comment by NotWeeb** [comment]
i believe this has been fixed in the latest update
