### ISSUE TITLE
Preview returns 404 when editing a bot

### ISSUE THREAD

**Issue by unbelievable-pizza** [DiscordBotList/issues#152]
#### Expected Behavior

Shows a preview of the bot page 

#### Observed Behavior

404 not found error 😩

#### Applicable Links or Attachments

https://imgur.com/bf0Sapk
https://imgur.com/a/hVvaLTm

#### Steps to Reproduce

1. Edit one of your bots
2. Click the preview button

**Comment by tonkku107** [comment]
Fixed
