### ISSUE TITLE
Video bug

### ISSUE THREAD

**Issue by Cairo2k18** [DiscordBotList/issues#153]
#### Expected Behavior

I expected my bot's page to load without the video box (as it doesn't have one).

#### Observed Behavior

The bot's page loaded with the video box on continuous buffer.

#### Applicable Links or Attachments

![Image of bug](https://cairo2k18.xyz/src/fnyig.png)
[Link to bug](https://discordbots.org/bot/437439973751521280)

#### Steps to Reproduce

1. Open Discordbots.org
2. Go to a bot's page
3. Look at where the video usually appears

#### Web Browser and Version

Firefox 62.0.2 (20180920131237)

#### Operating System and Version

Microsoft Windows 10 Home | Version 10.0.17134 Build 17134

#### Screen Resolution

1920x1080

#### Additional Information/Comments

n/a

**Comment by tonkku107** [comment]
That's an ad
