### ISSUE TITLE
Server List Showing Incorrect Member Count

### ISSUE THREAD

**Issue by Deakula** [DiscordBotList/issues#155]
#### Expected Behavior

I expected to see my server listed with 1680 users

#### Observed Behavior

Instead I found my server listed with 599 users

#### Applicable Links or Attachments

[My server listing](https://discordbots.org/servers/461605631657377792)
[The actual member count on my server](https://i.imgur.com/CCBTuzq.png)

#### Steps to Reproduce

1. Open https://discordbots.org/servers/461605631657377792
2. Observe member count as 599
3. Join my server, notice member count Rommy Bot is displaying is 1600+ (also reflected in the Server Settings)

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

**Comment by NotWeeb** [comment]
thanks for reporting should be fixed in upcoming update
