### ISSUE TITLE
Add paypal buttons instead of add webhook

### ISSUE THREAD

**Issue by dondish** [DiscordBotList/issues#160]
#### Expected Behavior

 To show multiple related webhook buttons. 

#### Observed Behavior

Instead, I found these add PayPal buttons

#### Applicable Links or Attachments

![Add Paypal](https://i.imgur.com/Z101gR0.png)

#### Steps to Reproduce

1. Open donatebot.io
2. Go to any server settings
3. Go to the settings tab
4. Look at the webhook

#### Web Browser and Version

Google Chrome Version 69.0.3497.100

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080
1370 x 768

**Comment by jczstudios** [comment]
Issue has been fixed, thank you for reporting!
