### ISSUE TITLE
Bot Page Video Doesn't Display

### ISSUE THREAD

**Issue by Samcool236** [DiscordBotList/issues#166]
#### Expected Behavior

The Video should appear on the bot page

#### Observed Behavior

Nothing appears in the position where the video should be

#### Applicable Links or Attachments

[My Bot Page](https://discordbots.org/bot/436756232792178688)

#### Steps to Reproduce

1. Open Discordbots.org
2. Go to a Bot Page which is supposed to have a video attached

#### Web Browser and Version

Google Chrome Version 69.0.3497.100

#### Operating System and Version

macOS Mojave Version 10.14

#### Screen Resolution

1440x900

#### Additional Information/Comments

The link and privacy settings on the video have not changed since the issue occurred.

**Comment by tonkku107** [comment]
This has been fixed
