### ISSUE TITLE
Desktop App?

### ISSUE THREAD

**Issue by rainbownotfound** [DiscordBotList/issues#170]
#### Suggestion

I think a desktop app version of the DBL would be a fun idea. An app that has the same functionality as the website.

Supported platforms(If possible):
- Windows
- MacOS
- Linux

I don't have more ideas regarding this issue.

#### Applicable Links or Attachments

None.

**Comment by advaith1** [comment]
I don't see the point of this 🤔

**Comment by Oliyy** [comment]
We don't currently plan on doing this.
