### ISSUE TITLE
/bot/vanityURL/edit returns 404

### ISSUE THREAD

**Issue by fourjr** [DiscordBotList/issues#178]
#### Expected Behavior

I expected https://discordbots.org/bot/statsy/edit to work

#### Observed Behavior

Instead I found a 404 page

#### Steps to Reproduce

1. Open https://discordbots.org/bot/statsy/edit
2. View the page

#### Web Browser and Version

Firefox 62.0.3

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

https://discordbots.org/bot/statsy is a valid page
https://discordbots.org/bot/347006499677143041/edit is also a valid page

**Comment by Gelbpunkt** [comment]
Great idea, please consider adding this for all subpages such as /vote too 😊
