### ISSUE TITLE
Background for Certified bot cards

### ISSUE THREAD

**Issue by Xignotic84** [DiscordBotList/issues#179]
I suggest this in hopes that Certified bot developers would be able to add custom banner images for the top of their bot's card. The Discord Server List site has already implemented a wonderful example of how this could be applied to bots. This will allow the developers to express their creativeness and individuality for their bots. I believe this will provide more content and life for the Certified Bots and pages of DiscordBots.org.

Bot Card : https://xignotic.is-going-to-rickroll.me/i/41hRvzewasmSyQ.png
What you can change your Bot Card to look like: https://xignotic.is-going-to-rickroll.me/i/y1Wg8xBC_3Ttag.png
DSL : https://xignotic.is-going-to-rickroll.me/i/qDIpdsktB2Bm7Q.png

**Comment by NotWeeb** [comment]
+1

I think this would be neat for Certified bots.

**Comment by Oliyy** [comment]
This is now planned and nearly implemented! 💃
