### ISSUE TITLE
Unable to find server with tag.

### ISSUE THREAD

**Issue by Glitta** [DiscordBotList/issues#185]
#### Expected Behavior

I expected to find my server when using the Roleplay tag.

#### Observed Behavior

Instead I couldn't find it. It should of been in the 2nd-3rd page since it seems to be more members at the top and lower. 

#### Web Browser and Version

Google Chrome (I dont know how to find the version but its the newly updated one?)

#### Operating System and Version

Windows 10 (again, unsure of version)

#### Screen Resolution

1366x768

**Comment by tonkku107** [comment]
Not much information to go off of here.
