### ISSUE TITLE
Widget customization adds 1 more upvote

### ISSUE THREAD

**Issue by IWasAndrerstajn** [DiscordBotList/issues#188]
#### Expected Behavior

Should't it be accurate?

#### Observed Behavior

It's not accurate by one upvote

#### Applicable Links or Attachments

Link to bot: https://discordbots.org/bot/399720101370396672

#### Steps to Reproduce

1. Open Discordbots.org
2.
Cant really help with this since its only for the developer/submitter of the bot

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 7 64bit

#### Screen Resolution

1920x1080

#### Additional Information/Comments
None

**Comment by tonkku107** [comment]
Widgets use the total vote amount instead of the monthly.
