### ISSUE TITLE
The page buttons don't work on some pages

### ISSUE THREAD

**Issue by Merlintor** [DiscordBotList/issues#192]
#### Expected Behavior

I expected that clicking the button for Page 2 brings me to page 2.
#### Observed Behavior

On some pages (e.g https://discordbots.org/servers/tag/support-server)  the Page 2 button brings you to page one, Page 3 to Page 2, Page 4 to Page 3.

#### Applicable Links or Attachments

https://discordbots.org/servers/tag/support-server
![image](https://user-images.githubusercontent.com/33966852/47785178-3399e280-dd08-11e8-95d7-641a2d6ea4df.png)

#### Steps to Reproduce

1. Open https://discordbots.org/servers/tag/support-server
2. Click the Page 2 button at the bottom of the page

#### Web Browser and Version

Google Chrome Version 70.0.3538.77

#### Operating System and Version

Windows 10

**Comment by Merlintor** [comment]
The links are right so I think it's a backend problem...

![image](https://user-images.githubusercontent.com/33966852/47785353-c63a8180-dd08-11e8-9edf-7c3cca5eca51.png)

**Comment by NotWeeb** [comment]
Can we confirm whether or not this is still a bug? I've attempted to reproduce this with no success.

**Comment by Merlintor** [comment]
Seems to be fixed.
