### ISSUE TITLE
mod-log bot owner pings

### ISSUE THREAD

**Issue by fatchan** [DiscordBotList/issues#196]
#### Suggestion

I think #mod-log messages should include a ping/@mention to the bot owners whenever their bot is muted, kicked, etc. This would prevent people just asking "why bot mute" without checking (or even knowing to check)  #mod-log.

I know it is already included in the embed and shows up in search results, but it should be in the "content" part of the message so it actually sends a notification to the bot owners.

#### Applicable Links or Attachments

The discord server

**Comment by tonkku107** [comment]
Duplicate of #27
