### ISSUE TITLE
Suggestion: Vote page redirect urls

### ISSUE THREAD

**Issue by NovusTheory** [DiscordBotList/issues#20]
#### Suggestion

So individual vote checking and webhooks are a thing. What about the ability to have redirect urls on the vote page? This could for example be used with popups on a bots website and then have the ability to redirect back with a `?success=true` sort of variable and then the user info passed with it.

The purpose behind this is maybe bots have their own website and can implement some sort of button or use it however they want to either require or just have an upvote button. This could also be linked to a popup window (A popup window can make use of polling the url so when it redirects it could avoid webhook delay or polling vote API which is beneficial to Single Page App websites) or a regular tab redirect and the website can check the query parameters for info. Another way this could be used is just the ability to include `redirect_uri` in the vote link and then when a person votes it can still send a webhook (possible conflict) but it can directly send them to a callback page on a website. A huge benefit to this is that it can decrease load on your servers if it's used properly (But this is under the assumption everyone would use it).

This sort of system is most prominent in OAuth applications and I can see a huge benefit here with this.

#### Applicable Links or Attachements

https://discordbots.org/bot/SOME_BOT_ID/vote?redirect_uri=REDIRECT_LINK (**Example usage**)

**Comment by Oliyy** [comment]
We don't think this will be a beneficial feature for DBL, we might revisit it in the future though.
