### ISSUE TITLE
Reminders for voting bots doesn’t work on Safari iOS

### ISSUE THREAD

**Issue by automaster6968** [DiscordBotList/issues#210]
#### Expected Behavior

After clicking “Yes, remind me” on the prompt that comes after voting a bot it should say the reminder setup was successful.

#### Observed Behavior

Pressing “Yes, remind me” does nothing.

#### Applicable Links or Attachments

![Screenshot of prompt](https://i.imgur.com/BFAKtKV.png)

#### Steps to Reproduce

1. Open Discordbots.org on iOS Safari
2. Go to the voting page for a bot that hasn’t been voted in the last 12 hours
3. Press Vote and try to accept the prompt to set up a reminder

#### Web Browser and Version

Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

#### Operating System and Version

iOS 12.1

#### Screen Resolution

1136x640 (iPhone SE)

#### Additional Information/Comments

N/A

**Comment by tonkku107** [comment]
Safari doesn't have notification support. If you wish to use notifications, you have to download another browser such as Google Chrome from the app store.

**Comment by automaster6968** [comment]
Then I suggest to put a message saying that notifications are not supported on Safari iOS and to download an alternative browser like Chrome from the App Store.

**Comment by tonkku107** [comment]
I'll do that once I figure out why it's not giving you an error message like it's supposed to

**Comment by automaster6968** [comment]
The problem is also happening when using Chrome on iOS.
