### ISSUE TITLE
Error 504 when searhcing for bots with tag: Role Management 

### ISSUE THREAD

**Issue by BramEsendam** [DiscordBotList/issues#211]
#### Expected Behavior

I expected to find a list of bots that are tagged Role Management 

#### Observed Behavior

504 gateway error

#### Steps to Reproduce

1. Open Discordbots.org
2. Click on search box.
3. Click on tag.
3. Click on Role Management.
4. Click on search

#### Web Browser and Version

Google Chrome Version  70.0.3538.102

**Comment by tonkku107** [comment]
Extension of #189

**Comment by BramEsendam** [comment]
I've changed the *Steps to Reproduce* a bit. To make it clear that its not an extension of #189

**Comment by tonkku107** [comment]
I know it still is an extension of it. I'm keeping both issues tho and that comment is just marking it for me.
