### ISSUE TITLE
Server does not show on profile

### ISSUE THREAD

**Issue by Absentt** [DiscordBotList/issues#218]
#### Expected Behavior

I expected to find the server in My Profile after adding the bot Discord Server List Bot

#### Observed Behavior

Instead, it wasn't there.

#### Applicable Links or Attachments

http://prntscr.com/lt0xxi
http://prntscr.com/lt0yph

#### Steps to Reproduce

1. Authorise the bot
2. Check in https://discordbots.org/servers/me

#### Web Browser and Version

Google Chrome Version 70.0.3538.110

#### Operating System and Version

Windows 10

#### Screen Resolution

1920x1080

#### Additional Information/Comments

I would suspect it has something to do with the bot's perms, but even after giving it Administration rights, it still proceeded to not show up in "My Profile"

This is not a duplicate post because even after waiting since there's an apparent "delay" it still won't show up.

**Comment by NotWeeb** [comment]
fixed in update
