### ISSUE TITLE
Common Prefix/Command Suggestion

### ISSUE THREAD

**Issue by EmanSza** [DiscordBotList/issues#219]
Add Common Command Channel

#### Suggestion

I think we should add a Common Prefix/Command Channel because ..

- Users can test bot ping in large servers
- Improve the user experience
- Users Will be able to user !ping without spamming #test1 or #test3

**Comment by tonkku107** [comment]
Could you elaborate?

**Comment by ThatTonybo** [comment]
#bot-hell
