### ISSUE TITLE
Change the header to say "Join DBL" instead of "Join Discord"

### ISSUE THREAD

**Issue by Nathan-Webb** [DiscordBotList/issues#228]
#### Suggestion

We should change the header to say "Join DBL" because it causes an unnecessary point of confusion when people join the DBL server expecting to receive help for whatever bot they were currently on.

**Comment by Oliyy** [comment]
This seems more unclear

**Comment by Nathan-Webb** [comment]
How would it be more unclear? It seems that people are constantly confusing that button with the Support Server invite.

**Comment by Chew** [comment]
I mean anything we suggested is less unclear, but alright
