### ISSUE TITLE
Going to error 500 when I submit my server

### ISSUE THREAD

**Issue by thescaryspooky** [DiscordBotList/issues#232]
#### Expected Behavior

I expected to have my server up on the website.

#### Observed Behavior

Instead I was shown a screen telling me there was an error.

#### Applicable Links or Attachments

https://imgur.com/726IRnZ

#### Steps to Reproduce

1. Open Discordbots.org
2. Try to edit a server on your profile
3. Click submit

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

I have no clue why it isn't working, I have restarted the site many times, please answer when you can!

**Comment by NotWeeb** [comment]
fixed in update
