### ISSUE TITLE
Filtering by tags on the API doesn't work as expected  

### ISSUE THREAD

**Issue by Shea4** [DiscordBotList/issues#233]
#### Expected Behavior

I expected the endpoint to return only bots which include the filtered tag

#### Observed Behavior

Instead it returns bots regardless whether they have that tag or not

#### Applicable Links or Attachments

https://discordbots.org/api/bots?search=tags:economy&sort=monthlyPoints

#### Steps to Reproduce

1. Open https://discordbots.org/api/bots?search=tags:economy&sort=monthlyPoints
2. Look through bots until you see one which isn't in the filtered tag

#### Web Browser and Version

Google Chrome Version 71.0.3578.98

#### Operating System and Version

Windows 10 
Version 10.0.17134 Build 17134

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment]
It is `tag` and not `tags`
https://discordbots.org/api/bots?search=tag:economy&sort=monthlyPoints
