### ISSUE TITLE
Voting for the same bot may not have sense.

### ISSUE THREAD

**Issue by Saga-ra** [DiscordBotList/issues#240]
I think the option to vote repeatedly for the same BOT could be taken off because, if not, it just turns into a competition of who logs in more often to vote for a given BOT. The idea of voting, as I have knowledge of, is to know how many different people think a BOT is worth it; but if there are just six or seven persons who are constantly voting for it and it gets to the top it wouldn't have sense.

**Comment by tonkku107** [comment]
Did you mean bot?

**Comment by Saga-ra** [comment]
I meant BOT, yes. I have updated my message but I can't donit with the title.

**Comment by Gelbpunkt** [comment]
This is a core aspect of DBL and shouldn't be changed as it's how it works. You keep your users active, get popular, and they get ad income for votes. 7 people can't vote a bot up to the tops, that's ~210 possible votes a month. If only 100 users would vote every second day, you would have 1500 votes.

**Comment by Saga-ra** [comment]
One can know what I wanted to express, I obviously didn't say that literally.
