### ISSUE TITLE
Only letting me invite to one server

### ISSUE THREAD

**Issue by LucarioSerenity** [DiscordBotList/issues#242]
Hey Donatebot Developers, 

So, I was trying to set up Donatebot today. I went to the discord bot list, searched Donatebot and got to donatebot.io. I then tried to set up my discord server, LucarioSerenity Discord, and it said that I could only invite Donatebot to ThunderClan, my warrior cats fan server. I tried inviting it to that server and it brought up the server settings for selling roles, like usual, but not for LucarioSerenity Discord. I tried inviting it to both servers, kicking it from both servers and inviting it again. It also doesn't say on Donatebot.io that I can add another server. In the dashboard, it only showed ThunderClan. Please fix this, as I need Donatebot  to set up my server.

@LucarioSerenity (github)
or
@TheGreatLucarioSerenity#1388 (discord)
If you want, you can tweet me when you fix it at @lucarchuyt15629 on twitter.

Thanks!

**Comment by tonkku107** [comment]
Do you have manage server permissions in the server you're going to invite the bot to?

**Comment by LucarioSerenity** [comment]
Ohhhh, yes, i am, but i cant log in to the owner account because i lost the 2fa code for it so i made an alt account

**Comment by LucarioSerenity** [comment]
But i do have basically owner perms, like administrator and server mods
