### ISSUE TITLE
Scam Ads Problem

### ISSUE THREAD

**Issue by Luc1412** [DiscordBotList/issues#243]
#### Issue

There's a problem with advertising. Today a Free VBucks (Scam) page advertisement was displayed over my Fortnite Bot. This puts my bot in a bad link because I link to the bot website and the bot website links to a scam website ---> My bot finally links to a scam website. (This site is no direct scam where you put your phone number in and get a monthly subscription, but I'm sure that you aren't able to win anything)

It would be a good idea to find a better and more trustworthy advertising provider or to completely disable advertising for certified bots. 

It would be good if a solution could be found as soon as possible.

#### Applicable Links or Attachments

![Scam](https://i.imgur.com/WPVM0kG.png)

**Comment by tonkku107** [comment]
We're working on blocking all the scam advertisements.
However, the content of advertisements is out of the scope of this issue repository
