### ISSUE TITLE
Favor vanity URL where applicable.

### ISSUE THREAD

**Issue by Chew** [DiscordBotList/issues#250]
#### Suggestion

All over the place, the website wants me to stick to the /bot/:id page. When I vote on the vanity URL and click back, it just goes to /bot/:id. The edit and delete buttons are also /bot/:id redirects everywhere. It would be nice if it could redirect to the vanity URL to let users know it's better and more efficient than a bunch of numbers.

#### Applicable Links or Attachments

Soon, if required.

**Comment by tonkku107** [comment]
Extension of #178
