### ISSUE TITLE
Update button resets verified server listings

### ISSUE THREAD

**Issue by Tommyfoxy2** [DiscordBotList/issues#252]
**ServerID**: 414234792121597953

#### Expected Behavior

The server should be marked as Verified and published with info etc.

#### Observed Behavior

No longer published and all its info reset. Logged out and back in, the same thing. Checked by searching and verified server page and it's no longer there.

#### Applicable Links or Attachments

![Image of info reset and unpublished](https://i.imgur.com/dJ3f4Xm.png)

#### Steps to Reproduce

1. Edit your verified server listing
2. Use the update button
3. Your information is now all reset

#### Web Browser and Version

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

#### Operating System and Version

Windows 10

#### Screen Resolution

1440 x 900

**Comment by NotWeeb** [comment]
Thanks for reporting I'll look into this asap
