### ISSUE TITLE
discord account getting disabled for no reason

### ISSUE THREAD

**Issue by Roseundmary** [DiscordBotList/issues#253]
I have a friend who accounts keep getting disabled for no reason, he is a YouTuber and I know for a fact that he has not broken any code of conduct or rules. I have a feeling someone is reporting his account for things he has not done wrong. 

Jamsteo#9925 @Jamsteo#8315  are the 2 accounts that got disabled. 
If you need any more information contact me at ilovemusic5685@gmail.com Or on yalls server which is 
Kira_da_girl#9476

**Comment by tonkku107** [comment]
This repo is for bug reports and feedback, not for ban appeals.
If your friend has been banned from discordbots.org and our Discord servers, they can email `appeals@discordbots.org`.
If their account has been disabled from the entirety of Discord, we are Discord Bot List, not affiliated with Discord. You'll need to sort this out with Discord support.
