### ISSUE TITLE
Suggestion - Tutorials for new developers. 

### ISSUE THREAD

**Issue by Arthurdw** [DiscordBotList/issues#256]
#### Suggestion 
Add a place in the discord server where users (new developers) can get information on how to create a discord bot.
Just like the page on the DBL github page but since almost no one knows about that page and a lot of people don't know where to start I think this would be a good idea. 

The github page where I'm pointing to is the [tutorial page](https://github.com/DiscordBotList/DBL-Tutorials).

**Comment by tonkku107** [comment]
The FAQ has a section on "How do I code a bot? Where do I start?"
