### ISSUE TITLE
Bot page avatar not updating

### ISSUE THREAD

**Issue by th0mk** [DiscordBotList/issues#258]
#### Expected Behavior

My bot has a feature where it features a song or artist any of our users is listening to every hour. This changes the profile picture of our bot, and the information of the featured song/artist can be requested with a command.
What I would expect to happen is the avatar on the [bot page](https://discordbots.org/bot/356268235697553409) updating when the profile picture changes.

#### Observed Behavior

On the bot page the profile picture is broken. This is probably because the url to the avatar doesn't get updated as often.

#### Applicable Links or Attachments

[Github repo from bot](https://github.com/Bitl/FMBot_Discord)
[Bot page](https://discordbots.org/bot/356268235697553409)

#### Steps to Reproduce

1. Open Discordbots.org
2. View bot page

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

The bot doesn't have the Discord Bots API implemented yet, but I'm planning to add it soon. 
I'm not sure how you guys handle avatar updates, but maybe a feature in your API that updates the user info would be a solution?

**Comment by tonkku107** [comment]
Your bot has been kicked from the Discord Bot List server which is why the avatar isn't automatically updating. This is not a bug.

**Comment by th0mk** [comment]
Ah okay, thanks for responding so quickly. I've spotted the reason why it was kicked (Case #4552). Once I have fixed that, who can I contact for an appeal or should I just appeal here?

**Comment by tonkku107** [comment]
You can contact any moderator.
