### ISSUE TITLE
Slider Alternative

### ISSUE THREAD

**Issue by Art3miss** [DiscordBotList/issues#260]
#### Suggestion

Adding an option to type the desired donation amount as opposed to using a slider (or only using a slider) would be a good QoL addition especially for mobile users who may find it difficult to select the exact number they want.

#### Applicable Links or Attachments

None

**Comment by techied** [comment]
Even on a desktop it is impossible to select a single dollar amount and instead I find myself jumping up and down by $4-5 even while using the arrow keys. Doesn't seem like it would be that hard to implement.

**Comment by jczstudios** [comment]
We've added the option to choose a custom price, just click the box with the price and type it in!
