### ISSUE TITLE
Able to apply for certification with certified bot

### ISSUE THREAD

**Issue by Chewsterchew** [DiscordBotList/issues#261]
#### Expected Behavior

My certified bot to not appear.

#### Observed Behavior

it did

#### Applicable Links or Attachments

![Image of the meme](https://cdn.discordapp.com/attachments/148195924567392257/542552266318675981/image0.jpg)

#### Steps to Reproduce

1. Open Discordbots.org/certification with a certified bot
2. open drop down

#### Web Browser and Version

No idea but does it matter

#### Operating System and Version

iOS 

#### Screen Resolution

Small

#### Additional Information/Comments

It is epic

**Comment by tonkku107** [comment]
I hid already certified bots from the dropdown.
You wouldn't have been able to submit the application, there was already a check in place before.

**Comment by Chewsterchew** [comment]
Cool, thanks, but seemed a bit redundant, good failsafe though 😃
