### ISSUE TITLE
Notify developers when their bot gets muted, kicked or banned

### ISSUE THREAD

**Issue by WabaDev** [DiscordBotList/issues#27]
#### Suggestion

Maybe send a DM to the bot developer when his or her bot gets muted, kicked or banned and have the reason stated allowing for the issue to be fixed without the developer having to look through the logs channel in search for his bots case to find the reason

#### Applicable Links or Attachements

None

**Comment by tonkku107** [comment]
I am not going to implement this to Luca.

Having your bot muted or kicked from the server isn't the end of the world. You don't even have to fix the issue.
