### ISSUE TITLE
Option to send a link to a selected product

### ISSUE THREAD

**Issue by RealBlackB1RD** [DiscordBotList/issues#270]
# Suggestion #

I think adding an option to send a link to a selected product like this:
`https://donatebot.io/checkout/server_id/role_id`

will be very helpful for people with few plans that want to feature them somewhere like a special Facebook Plan or Twitter Plan that is only for Facebook or Twitter users so they just click the link and need only to continue with PayPal.

**Comment by jczstudios** [comment]
Added! Read here for more details: https://app.gitbook.com/@donatebot/s/developers/~/drafts/-LjUSjexM45scRp4u-Ya/primary/link-directly-to-a-product-or-role
