### ISSUE TITLE
Problem when its on the checkout window

### ISSUE THREAD

**Issue by X1234XZ** [DiscordBotList/issues#273]
I set my bot a command called `f!donate` but when it brought me to the checkout window, it says

                                       500: Internal Server Error
                   500: Internal Server Error500: Internal Server Error
We were unable to process your request due to a server error, please try again.

           Please join our support server and provide error ID: 97HfQXM7Wd

**Comment by Xignotic84** [comment]
I am going to assume that this is for donate bot, If I am incorrect please do tell me.

**Comment by Xignotic84** [comment]
Due to the fact that this doesn't seem like a bug report relating to Donate bot or DBL, I will be closing this issue, you can reopen it and update it with a more detailed description explaining what you're having issues with if it relates to DBL, DSL or donate bot.
