### ISSUE TITLE
Large HTML table falling off the page

### ISSUE THREAD

**Issue by Fyk0** [DiscordBotList/issues#275]
#### Expected Behavior

The HTLM table should be contained within the border surrounding the main description portion
#### Observed Behavior

The description is "leaking" outside of the main border.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/45381083/53988426-466a5c80-40d8-11e9-840c-e319e6b275d9.png)
[bot profile](https://discordbots.org/bot/552734173803184128)

#### Steps to Reproduce

N/A

#### Additional Information/Comments

It may be because it's not a published-page.

**Comment by tonkku107** [comment]
This is the fault of your own css
