### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by kerocool111** [DiscordBotList/issues#279]
#### Expected Behavior

I expected bot to supmit form

#### Observed Behavior

Instead It gave me 500 error

#### Applicable Links or Attachments

![Image of the cat](https://discordbots.org/images/error.jpg
![image](https://user-images.githubusercontent.com/48702268/55293394-b90ae700-53bb-11e9-8e95-653e4abe3f6b.png)
)
![image](https://user-images.githubusercontent.com/48702268/55293396-c32ce580-53bb-11e9-8da1-5399a69ed1ce.png)

[Link to MySuperBot](https://discordbots.org/bots/mysuperbot)

#### Steps to Reproduce

1. Open Discordbots.org
2. ...

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

It might be because I visited a non existing page

**Comment by tonkku107** [comment]
The bug report wasn't filled in correctly

We are aware of the issues though... Try submitting again.
