### ISSUE TITLE
[DSL] Critical security breach

### ISSUE THREAD

**Issue by iDroid27210** [DiscordBotList/issues#28]
#### Expected Behavior

If you have `MANAGE_GUILD` permission on a server, you have access to the server page edition on the website. However, when you leave this server you should no longer have access to this feature.

#### Observed Behavior

We can still edit or delete the server entry **after** having left the server.

#### Steps to Reproduce

1. Be on a server where you have `MANAGE_GUILD` permission and which is registered on Discord Servers.

2. Leave the server.

3. Go on your [servers page](https://discordbots.org/servers/me).

4. Try to edit or delete the entry.

#### Web Browser and Version

Google Chrome - Stable build 66.0.3359.139 (64-bit)

#### Operating System and Version

Windows 10 Professionnal 64-bit (1803)

#### Screen Resolution

1920x1080

#### Additional Information/Comments

You should fix that **quickly** because it could be used for bad purposes (revenge after ban, etc).

**Comment by NotWeeb** [comment]
Hi, thanks for reporting the bug.
Everything should be fixed now, if anymore issues occur please let me know!
