### ISSUE TITLE
Offline Bot

### ISSUE THREAD

**Issue by cainy-a** [DiscordBotList/issues#280]
#### Expected Behavior

I expected the bot to add my server to my profile page.

#### Observed Behavior

Instead, it didn't work

#### Steps to Reproduce

1: Invite the bot

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

The bot was offline

**Comment by tonkku107** [comment]
Extension of #276
