### ISSUE TITLE
Can't add a new server

### ISSUE THREAD

**Issue by PeakAxis** [DiscordBotList/issues#282]
#### Expected Behavior

The server is listed to profile when bot added

#### Observed Behavior

No bots found, Still displaying "Add a new server" in profile

#### Applicable Links or Attachments

No link

#### Web Browser and Version

Google Chrome Version 75.0

#### Operating System and Version

Windows 10 pro

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment]
If you experience any issues with adding or editing your server, try to kick the bot from your server and then inviting it back again.
If the bot is offline for you in your server, it should automatically come back online within a few minutes (please allow up to 10 minutes before reporting).

If it's down longer than 10 minutes please reopen the issue and we'll work on it ASAP.

Thank you for your patience and we apologize for any inconveniences this caused
