### ISSUE TITLE
Add a disclaimer for long description

### ISSUE THREAD

**Issue by Luke-6723** [DiscordBotList/issues#286]
#### Suggestion

Add a disclaimer to the new bot page to state that the long description so that users will not come into the discord and complain that they spent hours on their description just to have their bot denied.

**Comment by tonkku107** [comment]
what

**Comment by Xignotic84** [comment]
same

**Comment by tonkku107** [comment]
See #78

**Comment by Luke-6723** [comment]
Basically this is to stop the "Is there anywhere my bot description is saved" when a persons bot is declined
