### ISSUE TITLE
Webhook Retrys {Suggestion}

### ISSUE THREAD

**Issue by Gamercord-Owner** [DiscordBotList/issues#287]
Add the ability for the webhook to retry if it fails with x amount of retrys.

- Good for those times there is a bot error and restart and the webhook fails

- Could have a set number of retrys like 3 times with an interval of 5-10 seconds

**Comment by Oliyy** [comment]
Hey, we already have the retry system. Currently, if a webhook fails to post it will try again in one minute, although I don't think we will be adding custom options to that anytime soon if we change our minds I'll try open the issue, thanks for your suggestion!
