### ISSUE TITLE
Add a starboard

### ISSUE THREAD

**Issue by ReKTDevlol** [DiscordBotList/issues#29]
#### Suggestion

I think we should have a starboard so that we can star messages as everyone has been asking for a starboard and it would be great if we had one as we all love starboards.

- Community Entertainment

Tonkku even said if he gets 100 moon emojis he will bring back the starboard but there is still no starboard™️, please bring back the starboard.

#### Applicable Links or Attachements
None

**Comment by CFTheMaster** [comment]
## N ### I #### C ##### E
**MEME**

**Comment by tonkku107** [comment]
Duplicate of #9
