### ISSUE TITLE
Has a delete server still posted on the website 

### ISSUE THREAD

**Issue by MrPoly** [DiscordBotList/issues#291]
#### Expected Behavior

I'm supposed to see my one only server [Core-Bot | Support] , not two.

#### Observed Behavior

Both servers are posted. One I think is a delete server, and if so I would like to request it being removed from my list.

#### Applicable Links or Attachments

![Image of the cat](https://cdn.discordapp.com/attachments/546507495741456408/573890591696355348/unknown.png)
[Link to my delete guild page](https://discordbots.org/servers/508418923390304276)

#### Web Browser and Version

Version 73.0.3683.103 (Official Build) (64-bit)

#### Operating System and Version

Windows 10 1809

#### Screen Resolution

1366 x 768

#### Additional Information/Comments

I really don't know the state is of this server. If its deleted (which I think it is) Can you remove it off my Discord Servers list? And if its not a deleted server, can you please let me know.  I went through my entire guilds list on discord and didn't come across this server.

**Comment by tonkku107** [comment]
This repo is for bug reports or feedback, not deletion requests
