### ISSUE TITLE
Vote Page CSS

### ISSUE THREAD

**Issue by Dr-Ari-Gami** [DiscordBotList/issues#293]
#### Suggestion

The ability to modify CSS on the vote page. In my case, I believe I made a good looking bot page, but the theme gets ruined if someone goes to the upvote page. Being able to set custom css on the page would be awesome!

#### Applicable Links or Attachments

N/A

**Comment by tonkku107** [comment]
The google analytics suggestion is a duplicate of #229

**Comment by Dr-Ari-Gami** [comment]
> The google analytics suggestion is a duplicate of #229 so I removed it from your post

Not Exactly. They were talking about Certified Developers, I am talking about regular ones.

**Comment by tonkku107** [comment]
You can comment your thoughts on that issue

**Comment by Oliyy** [comment]
Thank you for the suggestion but we will not be adding customizability to the voting page for the foreseeable future.
