### ISSUE TITLE
Show vote timer and fix dark theme

### ISSUE THREAD

**Issue by Dddsasul** [DiscordBotList/issues#295]
#### Suggestion

So since you already do a check to see if I voted, PLEASE also tell me how much there is until the next vote. The "vote again in 12 h" should be replaced with "vote again in X h Y m"

Also fix the dark theme, it's just a line of css.

![This is what I'm talking about](https://user-images.githubusercontent.com/13020101/58285995-7f9c9980-7db6-11e9-981b-e5cb5a60835f.png)

**Comment by tonkku107** [comment]
Duplicate of #104 

The white section is intentional. Dark theme bugs/suggestions are currently unsupported as it's pending for a major rewrite
