### ISSUE TITLE
CSS Having a stroke when darkmode enabled

### ISSUE THREAD

**Issue by Gofven** [DiscordBotList/issues#297]
#### Expected Behavior

Basically an issue with the CSS in the website having a stroke when you turn on dark mode when it comes to background images

#### Observed Behavior

https://discordbots.org/bot/410895395850551296
go to this links with and without dark mode and see the difference

#### Applicable Links or Attachments

https://discordbots.org/bot/410895395850551296
![image](https://user-images.githubusercontent.com/31272508/58832174-b1cbb800-864e-11e9-94e9-d019af0a7b5e.png)

#### Steps to Reproduce

1. Open Discordbots.org
2. Turn off Dark Mode
3. Go to https://discordbots.org/bot/410895395850551296
4. Go back
5. Turn on Dark mode
6. Go to https://discordbots.org/bot/410895395850551296

#### Web Browser and Version

Google Chrome Version latest

#### Operating System and Version

Windows 10 latest

#### Screen Resolution

2560x1440

#### Additional Information/Comments

Pls help is ugly

**Comment by tonkku107** [comment]
Bugs concerning individual bot descriptions are not valid. You (or the bot owner) will have to fix their own css styling.

Dark theme bugs/suggestions are currently unsupported as it's pending for a major rewrite
