### ISSUE TITLE
Add a new role called bot checker

### ISSUE THREAD

**Issue by ITheEqualizer** [DiscordBotList/issues#30]
#### Suggestion

Add some people so they will check new bot's and it will make bot approvals faster, Since lots of mods are busy and the amount of time processing bots is taking is really a lot.
With some new people in team, Mods can focus on server more and more and bot approval will be faster

#### Additional Information/Comments

It's better to find Bot Checkers from cert devs

**Comment by tonkku107** [comment]
lol no

**Comment by adx59** [comment]
f
