### ISSUE TITLE
Suggestion: Testing API.

### ISSUE THREAD

**Issue by Pettless** [DiscordBotList/issues#301]
#### Suggestion

I think you guys should add say a test bot. Where a user can use the test bots API token and test it out with voting and stuff like this without needing to wait for a bot to be verified and everything to simply test it out. This will...

- Make it a lot easier for people to test out the API.
- Make it easier for users to check if there code works.
- Make it easier for users to see if the API is good or not.
- also, make it a lot easier for users to see how this site works and improve user experience

**Comment by Xignotic84** [comment]
Because this suggestion causes problems we will not be implementing it. The issues that it can cause is abuse and other things that may effect the website and makes the api tokens redundant.
