### ISSUE TITLE
Upgrade for Luca

### ISSUE THREAD

**Issue by BowserV2** [DiscordBotList/issues#303]
#### Suggestion

Upgrade Luca to auto detect self bot embeds.

- Delete embed
- Auto ban the self bot

#### Applicable Links or Attachments
N/A
#### Example Code
`client.on("message", message => {
    if(!message.author.bot && message.embeds.length > 0) {
message.delete();
message.member.ban("Is filthy selfbot... Ew")
//Do other Luca ban stuff
}
})`

**Comment by Xignotic84** [comment]
First of all the method you're suggesting wouldn't work because embeds can be links and not discord embeds themselves.
