### ISSUE TITLE
Dark Mode Promoted Card Style Issues

### ISSUE THREAD

**Issue by Glasvegas** [DiscordBotList/issues#307]
#### Expected Behavior

Shouldn't be bright

#### Observed Behavior

Is way too bright

#### Applicable Links or Attachments

https://canary.discordapp.com/channels/264445053596991498/557980762675085333/603099111935180832
http://prntscr.com/ojju3r

#### Steps to Reproduce

1. Open Discordbots.org
2. look at an auction ad in dark mode
3. Get blinded

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

Oliy this is for you <3

**Comment by tonkku107** [comment]
This might quite literally be the worst bug report I've seen but ok

**Comment by Luke-6723** [comment]
Literally just came from tester-bugs to see this amazing issue creation, this is the best and most memey thing ive ever seen, thank you for your service @Glasvegas

**Comment by Glasvegas** [comment]
Not much else to really say is there? 😂

**Comment by tonkku107** [comment]
You could start by actually editing the rest of the template

**Comment by gabixdev** [comment]
I made a new dark theme for dbl like 2 weeks ago, just pinning it there if it might be useful. https://cdn.discordapp.com/attachments/556912126338269199/600645912762777600/dbl-dark.css
