### ISSUE TITLE
Show when the user has voted a bot when they are on the page.

### ISSUE THREAD

**Issue by jtsshieh** [DiscordBotList/issues#31]
#### Suggestion

Show when the user has voted a bot when they are on the page. When on the vote page, show some kind of notice on the vote button to notify the user that they voted already. Also on the main page, highlight the vote box if the user has already voted. 

#### Applicable Links or Attachments

[Link to the website](https://discordbots.org)

**Comment by Oliyy** [comment]
Users are able to check if they have already voted in the past 12 hours by going to /bot/:ID/vote and clicking the button. If they have they will receive a notice
