### ISSUE TITLE
Error 500 after trying to edit a server

### ISSUE THREAD

**Issue by MrCenny** [DiscordBotList/issues#313]
#### Expected Behavior

I expected to finish the editing of my discord server

#### Observed Behavior

Instead, I got a 500 error

#### Applicable Links or Attachments

![Image of the error](https://user-images.githubusercontent.com/49611200/62416827-24064c00-b642-11e9-8a5e-da0536958a21.png)

#### Steps to Reproduce

1. Open Discordbots.org
2. Go to the server page
3. Edit a server
4. Publish the edit

#### Web Browser and Version

Chrome 75

#### Operating System and Version

Windows 7

#### Screen Resolution

1600 x 900

#### Additional Information/Comments

Might be my internet speed, I don't really know.

**Comment by Xignotic84** [comment]
Try refreshing and resetting your cache if this is still and issue post your server ID and I'll take a look

**Comment by MrCenny** [comment]
It worked, thanks!
