### ISSUE TITLE
Add Bot via Website on Mac with Safari

### ISSUE THREAD

**Issue by triggeredLife** [DiscordBotList/issues#315]
#### Expected Behavior

I expected to add my bot via your website on my safari browser

#### Observed Behavior

Instead when I wanted to select the library the safari window stopped.

#### Applicable Links or Attachments

[Link to Add a Bot](https://discordbots.org/bot/new)
[Bildschirmaufnahme 2019-08-07 um 12.25.53.zip](https://github.com/DiscordBotList/issues/files/3476608/Bildschirmaufnahme.2019-08-07.um.12.25.53.zip)

#### Steps to Reproduce

1. Open discordbots.org/bot/new in safari
2. select any library (what probably won't work)

#### Web Browser and Version

Safari v. 13.0

#### Operating System and Version

Mac OS 10.15

#### Screen Resolution

1366×768

**Comment by tonkku107** [comment]
Safari v. 13 is in Beta and this is a bug with your browser. Please file a bug report for Safari.
