### ISSUE TITLE
Add World of Warcraft as a taggable game

### ISSUE THREAD

**Issue by CarlGroth** [DiscordBotList/issues#32]
#### Suggestion
Add World of Warcraft as a taggable game

World of Warcraft is a very popular game and blizzard offers an extensive API allowing for great commands. 

Discordbots already offers the ability to add several other, some less popular, blizzard games so this would fit in.

**Comment by Oliyy** [comment]
We currently don't see enough demand for this tag for it to be worth adding. Thanks for submitting this suggestion. We will certainly consider adding the tag in the future if the popularity picks up.
