### ISSUE TITLE
[bots] [voting] login redirecting back to tag-page

### ISSUE THREAD

**Issue by Fyk0** [DiscordBotList/issues#320]
#### Expected Behavior

When not logged in to DiscordBots and click the **`^ n`** button on a bot card, you're sent to authorize Discord OAuth then redirected to the bot's vote page.

#### Observed Behavior

After logging in, you're sent back to that tag's page (if you're viewing from a tag).

#### Steps to Reproduce

0. Log out of DBL.
1. Visit `/list/certified`.
2. Click the `^ n` button to vote for the bot.
3. Click `Login` to approve Discord OAuth
4. Once approved, you're redirected back to `/list/certified` instead of the bot's vote page.

**Comment by tonkku107** [comment]
Extension of #167
