### ISSUE TITLE
Browser keeps infinitely requesting blocked asset urls such as server avatars

### ISSUE THREAD

**Issue by VeikkoLehmuskorpi** [DiscordBotList/issues#321]
#### Expected Behavior

I expected to see a broken image icon as the server avatar when the asset url has been blocked

#### Observed Behavior

Instead the browser keeps requesting the asset which quickly results in thousands of network requests

#### Steps to Reproduce

1. Block cdn.discordapp.com domain
2. Navigate to https://discordbots.org/servers
3. Observe the avatars which are loaded from the discordapp.com domain

#### Web Browser and Version

Google Chrome 

#### Operating System and Version

Windows 10

#### Screen Resolution

2560 x 1440

#### Additional Information/Comments

This issue stems from the fact that I am using the Privacy Badger browser extension which blocks tracking cookies, but that's irrelevant - this shouldn't happen when an asset cannot be loaded

**Comment by tonkku107** [comment]
The icons are set to load a default avatar image from discord when loading the real icon fails. The issue is caused by your extension and is therefore not a valid bug.

**Comment by VeikkoLehmuskorpi** [comment]
A blocked asset should not be requested thousands of times when the request for it fails. It **is** a valid bug, just not one you care about.
