### ISSUE TITLE
Unable to vote

### ISSUE THREAD

**Issue by dystopiaglory** [DiscordBotList/issues#322]
#### Expected Behavior

I expected to be able to vote every 12 hours.

#### Observed Behavior

Instead I was unable to, even after several days of waiting.

#### Applicable Links or Attachments

![Voting Error](https://user-images.githubusercontent.com/46277809/63925900-c0343080-c9ff-11e9-9767-194aa082f47b.jpg)

#### Steps to Reproduce

1. Open Discordbots.org
2. Select a bot, any bot.
3. Attempt to vote.

#### Web Browser and Version

Samsung Internet, Ver. 9.4.00.45

#### Operating System and Version

Samsung Galaxy S9, Android 9.0

#### Screen Resolution

2220x1080

#### Additional Information/Comments

I've waited several days, and attempted to vote with various different bots but experience the same results.

**Comment by lordofwars** [comment]
I am experiencing the same exact situation but with Samsung Galaxy S8 and attempting to upvote Idle RPG Bot.

**Comment by tonkku107** [comment]
Please reopen if this issue happens again
