### ISSUE TITLE
DBL Discord Authentication logs me out after 24 hrs

### ISSUE THREAD

**Issue by AdamHebby** [DiscordBotList/issues#328]
#### Expected Behavior

Expected to be able to vote without having to log back in within after 24 hours of logging in previously (sometimes with a vote after 12 hours) - usually no more than 72 hours between vote, usually as few as 24 hours later.

#### Observed Behavior

Had to log back in to vote after > 24 && < 48 hours between logging in previously.

#### Applicable Links or Attachments
N/A

#### Steps to Reproduce

1. Open Discordbots.org (from a Google Chrome Desktop notification)
2. Try to vote
3. Get a notification to log in
4. Log in
5. Vote for [RocketLeagueUnited](https://discordbots.org/bot/533387216370532353)
6. Repeat in 24 hours

#### Web Browser and Version

Google Chrome version 77, full details here: https://www.whatismybrowser.com/w/MBNC2SD

#### Operating System and Version

Windows 10 build 1903

#### Screen Resolution

1920px x  1080px * 2

#### Additional Information/Comments

I am not clearing my cache, running CCleaner or anything like that. The only thing I do is turn off my PC every night, but I have experienced this when I haven't done that.

Mods in DBL have not experienced this.

**Comment by tonkku107** [comment]
This is intended behavior

**Comment by nightsurge** [comment]
> This is intended behavior

Any reason for this intended behavior? I agree it is quite annoying to have to re-auth to a website every day, rather than some form of longterm session/refresh token usage to prevent this.

**Comment by tonkku107** [comment]
@nightsurge go to #329
