### ISSUE TITLE
Server Count Error

### ISSUE THREAD

**Issue by Jay-2018** [DiscordBotList/issues#33]
#### Expected Behavior

I expected to find my bot SnowFlakes Server Count

#### Observed Behavior

Instead I found N/A

#### Applicable Links or Attachements

[Link to SnowFlakes Page](https://discordbots.org/bot/406352179415351297)

#### Steps to Reproduce

1. Open Discordbots.org
2. Search SnowFlake
3. Look at the one on the right, servercount is N/A

#### Web Browser and Version

Google Chrome Version 66.0.3359.139

#### Operating System and Version

Windows 8.1

**Comment by zBlakee** [comment]
It’s more than likely that you haven’t posted your bot’s server count to our [API](https://discordbots.org/api/docs) correctly. This is not an issue with DBL, you need to manually update your server count. For more help, you can visit the #api channel in the Discord server 👍
