### ISSUE TITLE
Website Copywrite in footer is 2018

### ISSUE THREAD

**Issue by AdamHebby** [DiscordBotList/issues#330]
#### Expected Behavior
Expected to see the following in the website footer
> ALL RIGHTS RESERVED © 2019

#### Observed Behavior

Saw:
> ALL RIGHTS RESERVED © 2018

#### Steps to Reproduce

1. Open Discordbots.org
2. Scroll down to the footer

#### Web Browser and Version

Google Chrome version 77

#### Operating System and Version

Windows 10 build 1903

#### Screen Resolution

1920 x 1080

#### Additional Information/Comments
N/A

**Comment by braindigitalis** [comment]
I am not a lawyer, but its my understanding this is more correct than updating it to 2019 or even 2020.

The copyright date should be the date the project was initially created not the current year, e.g. if someone contests when you started work on a project to claim they came up with it first, this notice at the footer is your legal statement that you attest you started it in year 'x'.

Just my 2 cents.

**Comment by AdamHebby** [comment]
Hmm I actually think you're right there!
