### ISSUE TITLE
The bot is not showing up on  "Your Profile"

### ISSUE THREAD

**Issue by Juvator** [DiscordBotList/issues#332]
It's a bit weird that I have to report my issues here and cannot get help with this in the discord.
It's probably a simpler problem it's confusing to me you are supposed to put such a problem on Github and specifically create an account for this.

**Comment by tonkku107** [comment]
Please provide more information about your bug report.
What bot is not showing up on your profile? Where are you viewing your profile (url)?

**Comment by marcorennmaus** [comment]
![https://luca.is-inside.me/fx2VYgvJ.png](https://luca.is-inside.me/fx2VYgvJ.png)

Looks like it was related to the DSL bot

**Comment by tonkku107** [comment]
Seems like this issue can be closed now then
