### ISSUE TITLE
Urban Dictionary command allowed outside of NSFW channels

### ISSUE THREAD

**Issue by AlexFlipnote** [DiscordBotList/issues#339]
## Suggestion
Let bots have an urban command without needing to have it under a NSFW filter.

### Why?
Urban Dictionary is well known as a large collection of user-made definitions to short terms like [wdym](https://www.urbandictionary.com/define.php?term=Wdym), relevant meme definitions like [joe mama](https://www.urbandictionary.com/define.php?term=Joe%20mama) and references to gay porn stars voice mixed with music like [gachi](https://www.urbandictionary.com/define.php?term=Gachi)

All though urban dictionary has a few NSFW definitions inside it, it shouldn't be considered as an entirely NSFW command. Urban has mostly SFW definitions with the slightest slurs around to add to the definitions, but other than that, pretty SFW.

If urban dictionary should be considered NSFW, why shouldn't wikipedia also be considered such? They host things like what [pornography](https://en.wikipedia.org/wiki/Pornography) is, the culture of [hentai](https://en.wikipedia.org/wiki/Hentai), [torture](https://en.wikipedia.org/wiki/Torture) and so much more, and yes, all of them include NSFW image examples inside them.

Why not as well deny bots to play YouTube music that has mentions the slightest thing that can and/or is sexual reference. A few examples are [50 Cent - Candy Shop ft. Olivia](https://www.youtube.com/watch?v=SRcnnId15BA), [Flo Rida - Whistle](https://www.youtube.com/watch?v=cSnkWzZ7ZAA), [Britney Spears - If U Seek Amy](https://www.youtube.com/watch?v=0aEnnH6t8Ts) or just a song that straight up says the n word 80% of the entire song called [Gangsta Rap - Ni\*\*a Ni*\*a Ni\*\*a](https://www.youtube.com/watch?v=pAaXzHJhA18)

Consider this as well, if other bot lists are removing the ruling as people get more of an idea how weird it is to add urban dictionary with NSFW filter, don't you think that DBL should also adapt with it? There's absolutely no reason to have it behind NSFW filter.

Sure you can find a few NSFW definitions on there, so why does Google, Bing and DuckDuckGo provide porn results as well with the right words connected to each other? I mean, this is the internet and just a few words, there's no images that are displayed inside urban dictionary.

## Example with DuckDuckGo
While having safe search on, you can still find porn if you use the right terms, like [this](https://i.alexflipnote.dev/9aNVr7a.gif) (The GIF does not show any suggestive content, however it does reference to one)

## Conclusion
Either enforce your NSFW rules and get more commands to use NSFW filters considering they can find things to the same level as urban dictionary, or just remove urban dictionary being required to have NSFW filter.

**Comment by eggsywashere** [comment]
this got me very mad, it's my favourite tv show
![2019-10-20_02-22-37](https://user-images.githubusercontent.com/13917975/67152511-8cc7a100-f2e0-11e9-8568-89ae5520eb99.png)

**Comment by VACEfron** [comment]
I approve, yes

**Comment by Xignotic84** [comment]
We've decided to close this issue and not change our policy behind our ruling against Urban Dictionary in non NSFW channels. This was decided by our team after discussions with Discord employees.

**Comment by Xignotic84** [comment]
After another discussion with the team, we've decided to no longer force Urban Dictionary commands to be locked to NSFW channels. You can read more about it [here](https://discordapp.com/channels/264445053596991498/769566680807899156/769584842370449439) in our [Discord Server](https://discord.gg/dbl).
