### ISSUE TITLE
Addition of two production ready libraries to the list of possible libraries on the website

### ISSUE THREAD

**Issue by braindigitalis** [DiscordBotList/issues#344]
#### Suggestion

can i please suggest that you add some libs to your list of possible libraries? I recommend addition of: ``aegis.cpp`` and ``sleepy_discord``, C++ discord libraries used in a few production bots, aegis is used in mine.

- These libraries are being used in production
- Right now, i have to put 'custom library'. It isn't and I think this does the library author a disservice on my part.

#### Applicable Links or Attachments

[aegis.cpp](https://github.com/zeroxs/aegis.cpp)
[sleepy_discord](https://github.com/yourWaifu/sleepy-discord)

**Comment by tonkku107** [comment]
Our library list is based on the list found in [Discord API](https://discord.gg/discord-api).
