### ISSUE TITLE
NSFW ads on site

### ISSUE THREAD

**Issue by braindigitalis** [DiscordBotList/issues#345]
Please remove these nsfw ads from your website especially in pages for bots marked safe for work.

![Screenshot_20191107-132711](https://user-images.githubusercontent.com/1556794/68392794-83548a80-0162-11ea-8598-62d05fa073fc.jpg)

![Screenshot_20191107-132723](https://user-images.githubusercontent.com/1556794/68392820-90717980-0162-11ea-89a2-b9d69845df57.jpg)

**Comment by LazyNeko1** [comment]
Ads are based on what you search.

**Comment by braindigitalis** [comment]
This may be true in America but here in the UK we can opt out of personalised ads. This has the effect of just showing you any and every and because Google etc don't know what you like. 

Instead of hinting that perhaps users of your site are deviants, is it possible to block such ads from the site?

**Comment by LazyNeko1** [comment]
You can opt out of personal ads, but were always being watched and personal info is always going to be sold off. No matter the country.

And no dbl cannot block the ads. It's going through another service (not google from what I could tell.)
