### ISSUE TITLE
Server Count, vote count caching issue?

### ISSUE THREAD

**Issue by nightsurge** [DiscordBotList/issues#346]
#### Expected Behavior

When I view a bot's page, it should have consistent behavior, regardless of caching pattern. Example: If the cache hasn't been busted yet, and I refresh the page multiple times, the vote count and server count should show the same results every time. This is OK if it is not 100% up-to-date as long as each time the cache is set, it is consistent.

#### Observed Behavior

Each time I refresh the page, I get DIFFERENT values at various points in the cache lifecycle.
Example bot page: https://top.gg/bot/613818499285909504

First load, 9 servers, 1 vote.
Second load, 23 servers, 2 votes.
Third load, 30 servers, 2 votes.
Fourth load, 17 servers, 1 vote.
Fifth load, 42 servers, 2 votes.
Sixth load, 67 servers, 3 votes.

I tried in incognito mode and the displayed values were at least consistent, but much farther out of date.

The values on the Search Results appear to be the most updated/cleanest cache, however, the values on the actual bot description page are what seems to jump all over the place.

#### Steps to Reproduce

1. Go to https://top.gg/bot/613818499285909504
2. Observe the bot stats.
3. Refresh multiple times to see different results.

#### Web Browser and Version

Chrome 78
On FireFox, it started with 23 servers, 2 votes on first load, then second load was 62 servers, 3 votes. And stayed consistent. So maybe it's mostly a Chrome bug from visiting the page multiple times throughout the day?

#### Operating System and Version

macOS Mojave

#### Screen Resolution

1080p

#### Additional Information/Comments

I have viewed this page throughout the day, so if there is some sort of client side caching going on, maybe that is the problem?

**Comment by tonkku107** [comment]
Not a bug.

**Comment by nightsurge** [comment]
This is a bug. Clearly.

**Comment by nightsurge** [comment]
Whether or not you wish to fix it, or how high priority is one thing, but this is most definitely a bug.

**Comment by tonkku107** [comment]
If it was a bug we were not willing to fix, I would've used the wontfix tag instead.
