### ISSUE TITLE
See which tag was searched the most

### ISSUE THREAD

**Issue by ITheEqualizer** [DiscordBotList/issues#35]
#### Suggestion

Let the devs see which tags were searched the most so they can work on certain commands which are included in that tag, Like let them see Fun is the most used search tag or anything else

**Comment by Oliyy** [comment]
We aim to provide these statistics to developers in the future but for now, they are available for Discord Bots Partners. If you want to apply use this link: https://goo.gl/forms/J1A6fjyUtQe6oq1r2
