### ISSUE TITLE
Error 500 when updating server details on website

### ISSUE THREAD

**Issue by Fyrlex** [DiscordBotList/issues#351]
#### Expected Behavior

I expected my edits for the markdown page for my Discord Server to properly update.

#### Observed Behavior

Instead I found Error 500 displayed on the page

#### Applicable Links or Attachments

https://i.imgur.com/P9LyRhM.png

#### Steps to Reproduce

1. Open Discordbots.org
2. edit markdown for server description
3. submit

#### Web Browser and Version

Google Chrome Latest

#### Operating System and Version

Windows 10 x64

#### Screen Resolution

1920x1080

**Comment by Xignotic84** [comment]
Duplicate of #340
