### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Mikoo4219** [DiscordBotList/issues#362]
I think discord should more themes other than just Dark and Light, it could have themes such as:
- Dark and purple
-Light and blue
-And many others
Please if you see this comment make something, a lot of people want a discord that is appealing for themselfs

**Comment by Xignotic84** [comment]
This request is relating to Discord themselves. You can make a suggestion towards Discord [here](https://support.discordapp.com/hc/en-us/community/topics)
