### ISSUE TITLE
[Profile Accent Colour] Unexpected behaviour/bug

### ISSUE THREAD

**Issue by dukeofsussex** [DiscordBotList/issues#365]
#### Expected Behavior

Navbar colour is changed and used on every page.

#### Observed Behaviour

Navbar not only doesn't immediately change, but also uses a seemingly random colour from the list of previously entered colours.

#### Applicable Links or Attachments

![PAC](https://user-images.githubusercontent.com/9024599/78365500-79bf3980-75bf-11ea-8002-60522c28c170.gif)

#### Steps to Reproduce

1. Open https://top.gg/me/edit
2. Change the colour and submit
3. Refresh page to force navbar to change colour
4. Repeat steps 1-3 with different colours
5. Refreshing/Navigating the website causes the navbar to use random (old) colours.

#### Web Browser and Version

Firefox 74.0

#### Operating System and Version

Win 7

**Comment by tonkku107** [comment]
Not a bug. Old values are cached for some time
