### ISSUE TITLE
Show if a bot is verified by discord on the website 

### ISSUE THREAD

**Issue by kingschool9** [DiscordBotList/issues#366]
#### Suggestion

I think it should show if a bot is verified by discord's bot verification system. This can make users' choices more clear in which bot to invite knowing that these bots are checked by discord and are used by 75+ other servers. If you can't make a category for this, you can still show it on the bot page like Certified bot in order to inform users of this information.

**Comment by tonkku107** [comment]
There is no value to this information on the site because all bots in over a 100 servers will have to be verified in order to accept new servers.
