### ISSUE TITLE
Double Voting

### ISSUE THREAD

**Issue by ThomasAunvik** [DiscordBotList/issues#368]
#### Expected Behavior

Vote only once.

#### Observed Behavior

Double voting if selecting one of both alert options.

#### Applicable Links or Attachments

![](https://img.thaun.dev/o96u9.png)
![](https://img.thaun.dev/ase1u.png)
![](https://img.thaun.dev/a1rwy.png)
![](https://img.thaun.dev/it3cw.png)
![](https://img.thaun.dev/gd4wf.png)
![](https://img.thaun.dev/hsern.png)
Cant check myself, but. double vote should show up in the api too.
https://top.gg/api/bots/650197869990772736/votes

#### Steps to Reproduce

1. Open Discordbots.org
2. Choose a bot
3. Click upvote
4. If using chrome, disable alerts.
5. Click on "Yes, Remind me"
6. Message should state that you have double voted.

5 Click on No.
6. You have declined.

Both outcomes will double vote.
Not selecting any of them will single vote.

#### Web Browser and Version

Chrome 81.0.4044.122

#### Operating System and Version

Windows 10 19041.113

#### Screen Resolution
1920x1080

#### Additional Information/Comments

It might have been that it is double-sending request after navigating to the second page of voting.

**Comment by Xignotic84** [comment]
Votes during the weekend are doubled. You can read more about it here https://discordbots.org/api/docs#votes-multiplier
