### ISSUE TITLE
Add a rule against cross-bot voting incentives

### ISSUE THREAD

**Issue by bryan-d** [DiscordBotList/issues#372]
#### Suggestion

Allowing bot developers to incentivize voting for other bots to receive rewards in a separate bot is a big issue. It is very clear why this is a problem when you look at the front page.

As I understand it, the Dank Memer bot provides rewards for voting for the Octave and Apex Predator bots. This unnaturally allows popular bots to take control over the entire front page, regardless of the worthiness of the individual bots, solely because the popular bot is feeding all of the votes to the secondary bot.

As a more general change, I think that in order to maintain proper rankings there need to be rules in place to disallow third-party voting incentives. This would be any incentive that is not a direct reward from the bot that you're voting for. Mainly this applies to cross-bot voting, but could apply to real money incentives or things of that nature.

#### Applicable Links or Attachments

![Front Page](https://i.imgur.com/AFCKti0.png)
![Incentives](https://i.imgur.com/DmRCJPp.png)

**Comment by Xignotic84** [comment]
This has been brought to our attention earlier and is going to be discussed.
