### ISSUE TITLE
Bot Profile Picture Doesn't load

### ISSUE THREAD

**Issue by shinixsensei-dev** [DiscordBotList/issues#374]
#### Expected Behavior

Everything would load properly

#### Observed Behavior

My Bot Profile Picture doesn't seem to load

#### Applicable Links or Attachments

[Bot Page on top.gg](https://top.gg/bot/706935674800177193)

#### Steps to Reproduce

1. Open top.gg

#### Web Browser and Version

I used Chrome on both my Phone and my PC

#### Operating System and Version

Android 8, Windows 10

#### Screen Resolution

3840x2160
idk my phone res tho

**Comment by tonkku107** [comment]
The avatar of the bot had changed and needed an update. This can be done by simply submitting an edit for the bot.
