### ISSUE TITLE
Auctions Bidding

### ISSUE THREAD

**Issue by danymo1221** [DiscordBotList/issues#377]
#### Suggestion

Feedback of an auctions tester,  Aftet being an auctions tester for over a month Ive seen that only (nothing against) but mee6 keeps wining the front page and music every time. I'd personnaly see top.gg to think of another way or rule to allow the smaller bot teams or groups to get a chance to win on the front page without having to go into the thousands of their own pocket against a bot thats in millions of servers and half of its features require you to donate.

I suggest for you to find a better ad system more like pay per click and so on rather than a bidding.

#### Applicable Links or Attachments

Look at the auction logs and see front page for example.
[Link to the website]
https://discordbots.org

**Comment by tonkku107** [comment]
Feedback about auctions should go in the #tester-bugs channel
