### ISSUE TITLE
[DSL] Suggestion: Change handling of NSFW-Guild-images

### ISSUE THREAD

**Issue by Andre601** [DiscordBotList/issues#38]
#### Suggestion

The current system is - as far as I understanding it - adding the label `nsfw` making the Guild-image/icon blurry and you need to hover over it to be visible.
This is good, but not always wanted, because a Guild may have NSFW-stuff, but their icon could be SFW.
Changing the system to something like this:
- [ ] Image is NSFW

would be imo better.
You could warn users on save, that not checking the option, while the image being NSFW, can result in a removal of the Guild from the list (or what other punishment you would do in that case).

#### Applicable Links or Attachments

No real links for examples or so....

**Comment by NotWeeb** [comment]
thanks for your suggestion

**Comment by tonkku107** [comment]
Closing this as NSFW content is no longer allowed
