### ISSUE TITLE
Luca doesn't DM you if you delete your bot

### ISSUE THREAD

**Issue by lumap** [DiscordBotList/issues#380]
#### Expected Behavior

If you delete your bot, Luca should DM you with "Your bot <@ID> has been deleted", like it does if a bot is deleted and that you are listed as co-owner

#### Observed Behavior

You don't get DM'd

#### Applicable Links or Attachments

[Example of the DM Luca sent you when a bot that you co-own is deleted](https://cdn.lumap.me/o3zw6zkt.png)

#### Steps to Reproduce

1. Delete your bot on top.gg
2. Observe

#### Web Browser and Version

Discord Canary 60661

#### Operating System and Version

Windows 10 x64

#### Screen Resolution

1600x900

**Comment by tonkku107** [comment]
Not a bug. Luca will not DM the owner that deleted the bot.
