### ISSUE TITLE
Site footer copyright year wrong

### ISSUE THREAD

**Issue by th0mk** [DiscordBotList/issues#382]
#### Expected Behavior

Site footer says ALL RIGHTS RESERVED © 2020 with the current year

#### Observed Behavior

Site footer says ALL RIGHTS RESERVED © 2018

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/9088316/82799239-02e54500-9e7a-11ea-81b1-5e6f17869ca4.png)

#### Steps to Reproduce

1. Open Discordbots.org

#### Web Browser and Version

Latest Chrome

**Comment by tonkku107** [comment]
Duplicate of #330
