### ISSUE TITLE
[DBL] Fake-Votes (Test-Votes) are counted in the discordbots.org/me page

### ISSUE THREAD

**Issue by Andre601** [DiscordBotList/issues#39]
#### Expected Behavior

The Bot(s) in [discordbots.org/me](https://discordbots.org/me) should show the number of votes.

#### Observed Behavior

The bot shows the number of real votes and the amount of test (fake) votes (See image 1)

#### Applicable Links or Attachements
**Image 1**: Bot in [discordbots.org/me](https://discordbots.org/me)
![Image 1](https://i.imgur.com/m47SLPe.png)

**Image 2**: Bot in the actual [Bot-page](https://discordbots.org/bot/425382319449309197)
![Image 2](https://i.imgur.com/orQvsiI.png)

#### Steps to Reproduce

1. Open Discordbots.org
2. Sign in to your Discord-Account (if not already done)
3. Click on your name

#### Web Browser and Version

Google Chrome Version 66.0.3359.181 (Official Build) (64-Bit)

#### Operating System and Version

Windows 10 Pro

#### Screen Resolution

1920x1080

#### Additional Information/Comments

I made some tests with the webhook, which resulted in the wrong Vote-count

**Comment by tonkku107** [comment]
The bot page right now shows monthly votes, while the old user page still shows all-time votes.
No bug here, just a confusion

**Comment by Andre601** [comment]
Not really.
Because my bot didn't have any votes in the past month (afaik) and even if, then it wouldn't be that high.
(7 votes this month and 12 total = 5 votes in the past month, which doesn't make sense)
