### ISSUE TITLE
"Server Locked" banner, browser cannot fetch images(DownTime?)

### ISSUE THREAD

**Issue by CRO-THEHACKER** [DiscordBotList/issues#391]
#### Expected Behavior

I expected to edit my server and browser keeps reloading, images not loading.

#### Observed Behavior

Getting a "Server Locked" banner over my server.

#### Applicable Links or Attachments

![Error](https://cdn.discordapp.com/attachments/704832368250454047/722659960625823774/unknown.png)

#### Steps to Reproduce

1. Open Discordbots.org
2. Go to "/servers/me"
3. Look at servers

#### Web Browser and Version

Mozilla Firefox for Ubuntu Version 77.0.1 (64-bit) on canonical 1.0

#### Operating System and Version

Ubuntu 16.04.6 LTS Codename: xenial

#### Screen Resolution

1366 x 768

**Comment by Xignotic84** [comment]
This report isn't valid since your server is locked you're not meant to be able to edit your server. You can contact me on discord Xignotic#0001 for more info about why your server is locked and how to resolve this.
