### ISSUE TITLE
Add feature to search detailed description of bots

### ISSUE THREAD

**Issue by Flam3rboy** [DiscordBotList/issues#393]
#### Suggestion

The thing is I'm searching for a bot with a special function/command and can't find it: _"No bots found :("_,
because top.gg doesn't search in the detailed description of the bot.
So bot makers could explain all commands in the bot description and users could search for a specific command.

**Comment by tonkku107** [comment]
This is already possible.
`longdesc: command`

**Comment by Flam3rboy** [comment]
Theo Mayen add a longdesc hint to the search options:

![image](https://user-images.githubusercontent.com/34555296/85522121-86bf5800-b605-11ea-8e29-da54064680cc.jpeg)
