### ISSUE TITLE
giveaways tag for bots

### ISSUE THREAD

**Issue by ronbr2151** [DiscordBotList/issues#399]
#### Suggestion

I think we should introduce more cats on the DBL Website because they ..

- Are cute
- Improve the user experience

and also are *better* than **dogs**

#### Applicable Links or Attachments

![Image of the cat](https://discordbots.org/images/error.jpg)
[Link to the website](https://discordbots.org)

#### Expected Behavior

I expected to find my bot MySuperBot

#### Observed Behavior

Instead I found this cat

#### Applicable Links or Attachments

![Image of the cat](https://discordbots.org/images/error.jpg)
[Link to MySuperBot](https://discordbots.org/bots/mysuperbot)

#### Steps to Reproduce

1. Open Discordbots.org
2. ...

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

It might be because I visited a non existing page

**Comment by Xignotic84** [comment]
Please format your suggestion correctly.
