### ISSUE TITLE
Crosspost Issues into #feedback

### ISSUE THREAD

**Issue by RethoughtSolutions** [DiscordBotList/issues#4]
#### Suggestion

I think we should cross post Issues to #feedback on the Discord Server.
That way we get more attention for this issue-board and can transit away from the feedback channel.
This could (probably) in 5 minutes be realized with GitHub webhooks for now.
Later on I'd suggest a more advanced system that also can display votes and is more well suited for our use-case.

#### Applicable Links or Attachments

https://developer.github.com/webhooks/

**Comment by Chewsterchew** [comment]
Just make a github webhook that ONLY sends Issues, so it's not difficult to implement
![38daf93d-7847-4e1a-badf-432340c58665](https://user-images.githubusercontent.com/8278263/39216798-b59659f0-47e2-11e8-8422-67515555c989.png)

**Comment by Oliyy** [comment]
Feedback channel has been deleted and we have no current plans for this.
