### ISSUE TITLE
"Click here to add your server!" does nothing

### ISSUE THREAD

**Issue by MattIPv4** [DiscordBotList/issues#40]
#### Expected Behavior
Clicking this text/panel should redirect to /servers/new

#### Observed Behavior
Upon clicking it redirects to /servers/me which does sweet fa as this is already where the user is.

#### Applicable Links or Attachements
[The linking text](https://i.dabbitpri.me/xtn1e4g1z1.png)
[The offending link](https://i.dabbitpri.me/q11iydmnuq.png)

#### Steps to Reproduce

1. Go to https://discordbots.org/servers/me
2. Have less than 4 servers listed
3. Click the "Click here to add your server!" text on one of the panels

#### Web Browser and Version
Firefox Quantum Developer Edition 61.0b6

#### Operating System and Version
macOS 10.13.4

#### Screen Resolution
2560 x 1600

**Comment by MattIPv4** [comment]
DSL issue.

**Comment by Chewsterchew** [comment]
Here's my bug report from a while back on this

Description of bug found: "No Server, click to add server" on the profile page Just leads to the profile page.
![img](http://files.chew.pw/bf54c21d1cfd2302c0fa64df1bd0b1c7.png)

Steps to repro:
1) Go here: https://discordbots.org/servers/me
2) Click "No Server, Click here to add your server"!
3) be upset and click Add a New Server, which works, apparently.

**Comment by NotWeeb** [comment]
fixed in next update
