### ISSUE TITLE
Proposal for Trending New Bots

### ISSUE THREAD

**Issue by israfilh** [DiscordBotList/issues#401]
I think the trending new bots place can be by vote ranking
1st pate ![Screenshot_1](https://user-images.githubusercontent.com/68771616/88546244-c3c3a380-d024-11ea-9c1a-10c7f6a6c491.png)
2nd page ![Screenshot_2](https://user-images.githubusercontent.com/68771616/88546251-c625fd80-d024-11ea-99f1-b9a312ff93cb.png)

[Link to the website](https://top.gg/list/new)

**Comment by ChillFish8** [comment]
you seem to forget that other bots go easily into the 1k+ votes a month and will just take away any chance for new bots. The system does also take into account Votes but not only by votes because that would be unfair in general.

**Comment by israfilh** [comment]
Trending New Bots yeri yeni botların toplandığı yer olduğu için haksızlık
olacağını düşünmüyorum

**Comment by tonkku107** [comment]
Your screenshots are from the new page where bots are sorted by the date approved, it has nothing to do with the trending new section on the front page.
