### ISSUE TITLE
top.gg logo not centered

### ISSUE THREAD

**Issue by Cynlis** [DiscordBotList/issues#404]
#### Expected Behavior

It to be centred and straight

#### Observed Behavior

But instead its off abit

#### Applicable Links or Attachments

![Bug](https://cdn.discordapp.com/attachments/735552284712239218/740642957455130714/unknown.png)

#### Steps to Reproduce

1. Open top.gg
2. hover over the logo in the top left

#### Web Browser and Version

Chrome latest version

#### Operating System and Version

Windows 10 2019

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment]
Looks centered to me :thinking:

**Comment by Luke-6723** [comment]
You're brain is playing tricks on you
![Proof](https://img.ichigo.uk/1n6tCa9WsLkI.png)

**Comment by marcorennmaus** [comment]
Probably should have specified on which axis it isn't centered, because it actually isnt

![image](https://user-images.githubusercontent.com/13847655/89740510-7fef8600-da89-11ea-8a7c-2693fd6f6987.png))
