### ISSUE TITLE
categories on the first page are not clickable any more(https://prnt.sc/tv2xg4)

### ISSUE THREAD

**Issue by oriapp** [DiscordBotList/issues#406]
#### Expected Behavior

I expected to find my bot MySuperBot

#### Observed Behavior

Instead I found this cat

#### Applicable Links or Attachments

![Image of the cat](https://discordbots.org/images/error.jpg)
[Link to MySuperBot](https://discordbots.org/bots/mysuperbot)

#### Steps to Reproduce

1. Open Discordbots.org
2. ...

#### Web Browser and Version

Netscape navigator 9.0.0.6

#### Operating System and Version

Windows 98 SE

#### Screen Resolution

320×240

#### Additional Information/Comments

It might be because I visited a non existing page

**Comment by Luke-6723** [comment]
what

**Comment by tonkku107** [comment]
Please fill in the details next time
