### ISSUE TITLE
Categories on the front page have cursor change to seem clickable but dont actually take you to page on click

### ISSUE THREAD

**Issue by Luke-6723** [DiscordBotList/issues#407]
#### Expected Behavior

It redirects you to the page associated with the tag

#### Observed Behavior

Nothing, you stay on the front page

#### Applicable Links or Attachments

![Video](https://img.ichigo.uk/nupgh5TT8Uoz.gif)

#### Steps to Reproduce

1. Open top.gg
2. click on the "Certified Bots" header

#### Web Browser and Version

Google Chrome | 84.0.4147.105 (Official Build) (64-bit) (cohort: Stable)

#### Operating System and Version

Windows 10 64x

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment]
Please fill in the expected and observed behavior sections

**Comment by Luke-6723** [comment]
Done!
