### ISSUE TITLE
Only two tags show on /servers/me

### ISSUE THREAD

**Issue by MattIPv4** [DiscordBotList/issues#41]
#### Expected Behavior
All three tags selected for a server should be shown

#### Observed Behavior
Only two of the three possible tags selected are shown

#### Applicable Links or Attachements
[The offending tags](https://i.dabbitpri.me/0ylcmr7r24.png)
[The selected tags](https://i.dabbitpri.me/ynobgmaimu.png)

#### Steps to Reproduce
1. Have a server listed on the site
2. Edit the server to ensure three tags are selected
3. Go to /servers/me and observe only two shown

#### Web Browser and Version
Firefox Quantum Developer Edition 61.0b6

#### Operating System and Version
macOS 10.13.4

#### Screen Resolution
2560 x 1600

**Comment by MattIPv4** [comment]
DSL issue.

**Comment by tonkku107** [comment]
2 tags showing on lists is intentional
