### ISSUE TITLE
Show three tags on each server in /servers/me

### ISSUE THREAD

**Issue by MattIPv4** [DiscordBotList/issues#42]
#### Suggestion
Please see issue #41 ...
Only two tags currently show which is quite misleading when three can be selected.
Might as well show all three on /servers/me and anywhere else that doesn't show all three.

#### Applicable Links or Attachments
[The displayed tags](https://i.dabbitpri.me/0ylcmr7r24.png)
[The selected tags](https://i.dabbitpri.me/ynobgmaimu.png)

**Comment by MattIPv4** [comment]
DSL suggestion.

**Comment by MattIPv4** [comment]
nailed it

**Comment by tonkku107** [comment]
Should DBL show all 6 tags then? The space on those cards is quite limited.

**Comment by MattIPv4** [comment]
I would say no, that makes sense as there are so many, but on DSL as the limit is three it seems logical to display them all.
