### ISSUE TITLE
Non-hyperlinked link in the privacy policy

### ISSUE THREAD

**Issue by FishyFing** [DiscordBotList/issues#44]
#### Expected Behavior

I expected to be able to click this link in the privacy policy

#### Observed Behavior

I cannot click this link

#### Applicable Links or Attachements

![Image](https://i.imgur.com/hxs48rv.png)
[Privacy policy](https://discordbots.org/privacy)

#### Steps to Reproduce

1. Open https://discordbots.org/privacy
2. Scroll down to `Tracking Technologies`

**Comment by tonkku107** [comment]
Not all links are created hyper
