### ISSUE TITLE
Edit a bot

### ISSUE THREAD

**Issue by mattsdot1** [DiscordBotList/issues#46]
#### Expected Behavior

I expected to edit my bot on the website normally

#### Observed Behavior

instead there is an error that says "Detailed description too short. Minimum 300 characters." when on the line, it says max: 140 chars

#### Applicable Links or Attachements

[Image of the error](https://gyazo.com/01787c5f53e05a328d09fac9db8d4559)
[Link to MySuperBot](https://discordbots.org/bot/422897155708026881)

#### Steps to Reproduce

1. Open Discordbots.org
2. go to a bot you created
3. press edit and try to edit anything and press submit and it will say that error

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

**Comment by ry0id** [comment]
MySuperBot is a placeholder, I think. You were supposed to change that to your bot's name so we know which one you're referring to. :)
Also, it's probably swapped around, as in: max is supposed to be 300, whereas minimum is supposed to be 140.

**Comment by ry0id** [comment]
No, wait.

**Comment by ry0id** [comment]
140 max. is your small description. 300 is your long description.

**Comment by ry0id** [comment]
hey theres ken

**Comment by zBlakee** [comment]
This is not a bug or an issue, simply a misunderstanding. As @ry0id kindly mentioned, your short description and long description are two different things; the short description will only allow for a **maximum** of 140 characters, whereas the long description requires a **minimum** of 300 characters (with no upper limit).

**Comment by ry0id** [comment]
yes

**Comment by ry0id** [comment]
that
