### ISSUE TITLE
"Discord Bot List" in meta values while sending a /vote link stay lowercase

### ISSUE THREAD

**Issue by bolsomito** [DiscordBotList/issues#48]
#### Expected Behavior

"Vote for *bot X* on Discord Bot List"

#### Observed Behavior

"Vote for *bot X* on discord bot list"

#### Applicable Links or Attachements

![Image](https://i.imgur.com/tUXKI6o.png)
[Link to Loritta](https://discordbots.org/bot/297153970613387264)

#### Steps to Reproduce

1. Send a link from DBL with `/vote` in the end
2. Observe

#### Web Browser and Version

Google Chrome Version 66.0.3359.181
Discord Canary Build nº 16139

#### Operating System and Version

Windows 7 SP1 Ultimate x64

#### Screen Resolution

1366x768

#### Additional Information/Comments

~do I really need to give all that information for an HTML case error? :sweats:~

**Comment by Oliyy** [comment]
I have now fixed this on our development instance and it will be pushed live within the next week. Thanks for reporting.
