### ISSUE TITLE
Bots kicked from a server cannot be unselected from displaying on the server page

### ISSUE THREAD

**Issue by L3NNY0969** [DiscordBotList/issues#50]
#### Expected Behavior

A kicked bot should be gone from my "top bots in this server" list

#### Observed Behavior

Instead it stays there and there is no way to remove said bot

#### Steps to Reproduce

1. Add a bot that is currently on your server to your displayed bots list
2. Kick the bot from your server
3. Try to edit your server and add/remove bots

**Comment by tonkku107** [comment]
You had some bots that you had kicked from your server stuck as selected. I removed them for you.

That stuck bug is already on our bug fix to-do list.

**Comment by Purpzie** [comment]
> You had some bots that you had kicked from your server stuck as selected. I removed them for you.

Could you please remove Fredboat from my server's page as well? #204 
Thank you in advance 😄

**Comment by tonkku107** [comment]
@Purpzie done

**Comment by LacunaAAA** [comment]
> 
> 
> You had some bots that you had kicked from your server stuck as selected. I removed them for you.
> 
> That stuck bug is already on our bug fix to-do list.

Would you also be able to fix this issue for server ID 339376237560463360? We no longer have Carbon. Thank you.
