### ISSUE TITLE
Personal description alternates 

### ISSUE THREAD

**Issue by ry0id** [DiscordBotList/issues#52]
#### Expected Behavior

I changed my description/status and expected it to stay like that.

#### Observed Behavior

After changing my description and going to a different site and, then, back to my profile, it changes back to my old one.

#### Applicable Links or Attachments

![Old description](https://owo.sh/be6379.png)
![What it's supposed to say](https://owo.sh/fcea27.png)

#### Steps to Reproduce

1. Open Discordbots.org
2. Change your description/personal status
3. Refresh the page OR visit another site and revisit your DBL profile

#### Web Browser and Version

Firefox Developer Edition (Version: 61.0b9)

#### Operating System and Version

Windows 10 Home (Version: 1803)

#### Screen Resolution

1920x1080

#### Additional Information/Comments

N/A

**Comment by tonkku107** [comment]
Issues on the old profile pages are not accepted.
Also that's caching, not an issue

**Comment by ry0id** [comment]
Old profile page?

**Comment by ry0id** [comment]
Were profile pages redesigned because if so, I still have the one in the screenshot above.

**Comment by tonkku107** [comment]
They are being redesigned

**Comment by ry0id** [comment]
Oh, okay. Makes sense then lol
