### ISSUE TITLE
Load the dark theme css by default to stop white flash

### ISSUE THREAD

**Issue by MattIPv4** [DiscordBotList/issues#54]
#### Suggestion

By default the dark theme css should be loaded and then removed if light mode is selected. Currently on page load there is a white theme flash before dark theme loads which is pretty blinding and very annoying when dark mode is enabled. Those using light mode can deal with a second of dark before light engages, that is far less blinding than a flash of light before dark.

**Comment by Oliyy** [comment]
We recognise the white flash is a problem but this is not how we intend to fix it.
