### ISSUE TITLE
Typo on blog with category list

### ISSUE THREAD

**Issue by zBlakee** [DiscordBotList/issues#55]
#### Expected Behavior

I expected to find "CATEGORIES" on the right hand side of the screen where the categories are listed

#### Observed Behavior

Instead I found that the title for the "categories" box is misspelt as "catagories"

#### Applicable Links or Attachments

[Link to the Blog](https://discordbots.org/blog)
#### Steps to Reproduce

`1.` Navigate to the [blog](https://discordbots.org/blog)
`2.` Scroll down to "CATAGORIES"

#### Web Browser and Version

Google Chrome - Version 66.0.3359.181 (Official Build) (64-bit)

#### Operating System and Version

Windows 10 1709

#### Screen Resolution

1920x1080

#### Additional Information/Comments

The "categories" endpoint (to access the different post categories) is also misspelt.
`https://discordbots.org/blog/cata/developer-spotlight`
I would've expected `blog/cate` instead of `blog/cata` (to better represent **cate**gories rather than **cata**gories), however this is a minor nitpick and doesn't affect anything

**Comment by advaith1** [comment]
This no longer applies since the blog has moved to Medium.
