### ISSUE TITLE
Webhook notification for adding the bot through the website

### ISSUE THREAD

**Issue by deprilula28** [DiscordBotList/issues#57]
#### Suggestion

Similar to how you already do webhook notifications for upvoting, I feel like having that but when someone adds the bot (or at least clicks the invite button) could be useful for those looking for statistics.<br>
Some suggestions for information given in the POST request:
- Logged in user (if any)
- Get queries, similar to voting

#### Applicable Links or Attachments

[Upvote webhooks](https://discordbots.org/api/docs#webhooks)

**Comment by Oliyy** [comment]
We're not planning on doing this webhook feature, but we will be making statistics on invite buttons etc available to developers soon.
