### ISSUE TITLE
Use https://feathub.com for suggestions, and keep bugs here

### ISSUE THREAD

**Issue by Chewsterchew** [DiscordBotList/issues#6]
#### Suggestion

All in the title, keep it simple. Feathub has a voting system, so it's basically a poor man's uservoice.

Pros:
- Keep "issues" to be just issues.
- Upvoting on Feathub.
- Need a github account to use feathub anyway.

Cons:
- Feathub has no API afaik, so #4 can't really be implemented.

#### Applicable Links or Attachements

[Link to the website](https://feathub.com)

Image of a cat (pic unrelated)
![Image of a cat](https://cdn.discordapp.com/attachments/155145799796391936/438460843806556170/404-kitty.png)

**Comment by Chewsterchew** [comment]
Yeah, ZenHub is brilliant. Problem is anyone who wants to see the *super special board* either needs to mozy on over to zenhub's site or get the extension.

ZenHub's just a necessity for github users overall, really.

But yeah, other than voting, Feathub does seem like an island connected by a lonely bridge (good analogy?) Let's get some more input

**Comment by tonkku107** [comment]
I don't like sorting suggestions by votes, so this wont happen, sorry
