### ISSUE TITLE
Server list style issue

### ISSUE THREAD

**Issue by Oliyy** [DiscordBotList/issues#63]
#### Expected Behavior
These buttons display normally

#### Observed Behavior

Instead I find this mess 

#### Applicable Links or Attachments

![Image of the display error](https://imgur.com/Y04XCPq)
[Link to Page](https://discordbots.org/servers)

#### Steps to Reproduce

1. Open Discordbots.org
2. goto Discord Servers

#### Web Browser and Version

Vivaldi | 1.14.1077.60 (Stable channel) (64-bit)

#### Operating System and Version

macOS Sierra - Version 10.12.6

#### Screen Resolution

2560x1600

#### Additional Information/Comments

Oliy pls fix / probably happens in bot list also

**Comment by tonkku107** [comment]
I love how the image is broken
