### ISSUE TITLE
Vote webhook not working

### ISSUE THREAD

**Issue by rubikscraft** [DiscordBotList/issues#64]
So the webhook for vote's doesn't work, it isn't sending any requests.

**Comment by deprilula28** [comment]
The test button doesn't work either.

**Comment by Lexxxtentacion** [comment]
Also getting this, no request is sent when someone votes or the test button is used. I used Postman to check that my server is 100% getting requests when I send them myself and handles them perfectly so this is not on my end.

**Comment by zBlakee** [comment]
Webhooks appear to be functional again. [Tonkku has claimed that they are working again](https://please.zbot.me/JDYbVih3.png), and after having other people vote for my bot, and using the "Test" button on the bot edit page, I can confirm that I am now correctly receiving webhooks from DBL. If anyone continues to encounter errors with webhooks, please open a new issue and we will take a look at it.
