### ISSUE TITLE
cannot update server link

### ISSUE THREAD

**Issue by PNWSONGDOG** [DiscordBotList/issues#66]
#### Expected Behavior

trying to update server link

#### Observed Behavior

 new link works everywhere else, but discordbots says its invalid.

#### Applicable Links or Attachments

https://discordbots.org/servers/450452589759430657 .

#### Steps to Reproduce

1. Open Discordbots.org
2. update server url. 
3. get error message about invalid link
4. alternatively, website wont let me hit submit at all.

#### Web Browser and Version

Google Chrome Version 5.10.5398

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

**Comment by PNWSONGDOG** [comment]
...anyone?

**Comment by PNWSONGDOG** [comment]
resolved by removing the bot and reinviting it, but, probably an issue that still needsto be resolved.

**Comment by Oliyy** [comment]
This should be fixed for future users.
