### ISSUE TITLE
only 3 tags? :( 

### ISSUE THREAD

**Issue by XeroCreator** [DiscordBotList/issues#67]
#### Suggestion
I believe having only 3 tags hinders the search capabilities too much. 
Searching Space Engineers only returns a few servers (mine is one as well) and this is a verified discord server. Allowing 2 more tags + adding Space Engineers would be nice, but other games as well, star citizen, etc as lots of servers do have a wide range of games they have discussions on.
Edit: there are other missing tags as well, a generic 'space' tag would be nice.
- More Tags Are cute
- More Tags Improve the user experience
and also are *MORE EPIC* than **less tags**

**Comment by Oliyy** [comment]
We might consider this in the future, but as of right now this is not something we are going to change.
