### ISSUE TITLE
Header tags are incorrectly colored in dark mode

### ISSUE THREAD

**Issue by Douile** [DiscordBotList/issues#69]
On mobile header elements (`<h1>`,`<h2>`...) are coloured incorrectly. Therefore the user cannot see them.

---

Page: Bot description

Issues:
- Headers
  - Expected output: Can see header elements
  - Actual output: header elements are invisible
  - ![Preview](https://i.imgur.com/OqF59cM.jpg)
- Tables
  - Expected output: fit to size of inner bot description, lots of text wrapping
  - Actual output: Extend off the side of the page
  - ![preview](https://i.imgur.com/puyfihG.jpg)

---

Platform: android 8.0.0 chrome 67.0.3396.81

**Comment by zBlakee** [comment]
This issue extends out to all devices, and is caused by having dark mode enabled. By default, the header tags are white, when they should be dark.
