### ISSUE TITLE
Hovering over an icon shows wrong text

### ISSUE THREAD

**Issue by qwertyquerty** [DiscordBotList/issues#7]
#### Suggestion

Fix dis tooltip

#### Applicable Links or Attachements

![image](https://user-images.githubusercontent.com/24400628/39221102-baf404fc-47fa-11e8-8851-a8e709ab209c.png)

#### Steps to Reproduce

hover your mouse over the new badge thing

#### Web Browser and Version

Google Chrome Version 65.0.3325.181

#### Screen Resolution

1920x1080

**Comment by zBlakee** [comment]
Can reproduce, also happens with the "Top Voted Bots this Month" section
![image](https://user-images.githubusercontent.com/26913683/39232136-a471819a-48af-11e8-9ca0-04c69216b11e.png)
