### ISSUE TITLE
Use minified css on the site

### ISSUE THREAD

**Issue by ohlookitsderpy** [DiscordBotList/issues#72]
#### Suggestion

I think we should use minified css on the site because:

- It is 10x faster™
- It improves the user experience™

**Comment by Chewsterchew** [comment]
👌 Cloudflare's got our back here
![image](https://user-images.githubusercontent.com/8278263/41923566-5554881a-792d-11e8-9ed2-b8ca7a1251df.png)

**Comment by ohlookitsderpy** [comment]
seems legit

**Comment by advaith1** [comment]
Do you mean minified CSS for DBL's built-in CSS, or user-added CSS?
Apparently, the Cloudflare setting only applies to CSS and JS *files*, not if it's inside the HTML.

**Comment by ohlookitsderpy** [comment]
i mean the built-in css

**Comment by Chewsterchew** [comment]
@advaith1 you could just minify the html, easy minify its contents

**Comment by Oliyy** [comment]
We are not planning on doing this at the moment, we are always rewriting aspects to help the site's performance including lots of caching so this won't contribute a noticeable amount to the site speed.
