### ISSUE TITLE
Form placeholders barely visible with dark theme

### ISSUE THREAD

**Issue by tonkku107** [DiscordBotList/issues#73]
#### Expected Behavior

I expected to see kinda lightish gray placeholder text

#### Observed Behavior

Instead it is dark gray and blends in with the form field background color

#### Applicable Links or Attachments
Dark theme: 
![Dark theme](https://boisbetterthanluca.xyz/i/bc8149.png)
Light theme:
![Light theme](https://boisbetterthanluca.xyz/i/51a100.png)

#### Steps to Reproduce

1. Go to a form with placeholders
2. Observe

#### Web Browser and Version

Google Chrome Version 68.0.3440.33 (Official Build) beta (64-bit)

#### Operating System and Version

Arch Linux

#### Screen Resolution

1920x1080 + 1280x1024

**Comment by NotWeeb** [comment]
will be fixed in next update, thanks for noting
