### ISSUE TITLE
Visual bug on server listing

### ISSUE THREAD

**Issue by cheesits456** [DiscordBotList/issues#75]
#### Expected Behavior

Emotes shown on server page as they appear within Discord

#### Observed Behavior

Emotes have odd aspect ratios and appear stretched out of shape - get even weirder when hovered over

#### Applicable Links or Attachments

![Image of expected vs observed](https://cdn.discordapp.com/attachments/446968021492432900/460227058606538784/unknown.png)

#### Steps to Reproduce

1. Open https://discordbots.org/servers/413486862175436812
2. Look at the emotes
3. Hover over the emotes (especially 'i' and '1')

#### Web Browser and Version

Google Chrome Version 67.0.3396.87 32 bit

#### Operating System and Version

Windows 10 Pro 1709 build 16299.125

#### Screen Resolution

1280 x 800

**Comment by Chewsterchew** [comment]
Probably due to how discord's emotes don't have to be perfect squares, but the site tries to make it a perfect square.. stretching.

**Comment by NotWeeb** [comment]
will be fixed in next update, thanks for the report
