### ISSUE TITLE
Separate Testing Channel For Bots With Common Prefixes

### ISSUE THREAD

**Issue by mets11rap** [DiscordBotList/issues#76]
#### Suggestion

Another testing channel like #testing1, but for bots with common prefixes such as "!" or "=".

-This would be beneficial because people would be able to do stuff like ping and the spam wouldn't annoy or interrupt people with snowflake prefixes testing their commands or having fun.

**Comment by Oliyy** [comment]
We don't need any more testing channels, developers can make their own testing servers.
