### ISSUE TITLE
Page listing is cut off

### ISSUE THREAD

**Issue by xXBuilderBXx** [DiscordBotList/issues#8]
#### Expected Behavior

The page for listing bots should display properly

#### Observed Behavior

The page lists bots into 4 colums but on the last row it only shows 1 bot

#### Applicable Links or Attachements

![Image](https://i.imgur.com/gDG0g6x.png)

#### Steps to Reproduce

1. Open Discbordbots.org
2. Got to any of these pages top bots, music, moderation, ect
You will notice that the list is cut

#### Additional Information/Comments

This does not happen on the certified bots page

**Comment by tonkku107** [comment]
Fixed
