### ISSUE TITLE
X-Frame-Options (iframe)

### ISSUE THREAD

**Issue by Merlintor** [DiscordBotList/issues#87]
#### Expected Behavior

I expected that iframes to external sites work

#### Observed Behavior

iframes to external sites work for some users and for some not.

#### Applicable Links or Attachments
![code](https://cdn.discordapp.com/attachments/466306542283784192/466624377996181515/unknown.png)
![working](https://cdn.discordapp.com/attachments/466306542283784192/466623209819865088/unknown.png)

![not working](https://cdn.discordapp.com/attachments/466306542283784192/466622995205455882/unknown.png)

#### Steps to Reproduce

1. Open https://discordbots.org/bot/xenon
2. Look if it's working for you

#### Web Browser and Version

Google Chrome Version 67.0.3396.99

#### Operating System and Version

Windows 10 1803

#### Screen Resolution

1920x1080

#### Additional Information/Comments

I already cleared my local cache and the cache of the destination dns server.

**Comment by tonkku107** [comment]
This is not a bug. You need to set the X-Frame-Options header on the website you are trying to iframe.
