### ISSUE TITLE
Background image on user profile is not displayed

### ISSUE THREAD

**Issue by napstr** [DiscordBotList/issues#89]
#### Expected Behavior

The Background URL is loaded / displayed.

#### Observed Behavior

The background URL is not loaded / displayed.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/6048348/42739389-c3532010-8896-11e8-9304-1cb5faed3dc9.png)

#### Steps to Reproduce

1. go to any user profile

#### Web Browser and Version

latest Google Chrome, latest FF

#### Operating System and Version

kubuntu 18.04

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment]
Not a bug. Backgrounds are currently disabled

**Comment by napstr** [comment]
Fair enough, but shouldn't this still result in some kind of action?
Either reenabling the backgrounds, or hiding the setting?
