### ISSUE TITLE
Bring back starboard

### ISSUE THREAD

**Issue by RethoughtSolutions** [DiscordBotList/issues#9]
#### Suggestion

I think we should introduce the Starboard again. People seem to enjoy it and it doesn't hurt anyone I guess.

Starboards are:
- Fun
- Enhance the user experience

**Comment by MrJacz** [comment]
+1

**Comment by YorkAARGH** [comment]
Misaki can run it :p

**Comment by xXBuilderBXx** [comment]
![Image](https://i.imgur.com/mH2Dnwg.png) thonk

**Comment by tonkku107** [comment]
![](https://cdn.discordapp.com/attachments/396848636081733632/438795622443646976/unknown.png)
