### ISSUE TITLE
'Top' list does not filter out NSFW bots

### ISSUE THREAD

**Issue by Mstrodl** [DiscordBotList/issues#91]
#### Expected Behavior

NSFW bots would not be shown anywhere

#### Observed Behavior

They show anyways

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/6877780/42820127-5d9fd764-89a3-11e8-90cf-e67dd733bd4b.png)

#### Steps to Reproduce

1. Navigate to [https://discordbots.org/list/top?page=3](https://discordbots.org/list/top?page=3) and find the bot with the NSFW tag, prominently displayed

#### Web Browser and Version

Irrelevent

#### Operating System and Version

Irrelevent

#### Screen Resolution

Irrelevent

#### Additional Information/Comments

Probably because you didn't plan on ever needing to do something like this so the code to fetch bots is duplicated all over the place which I would fix if the project wasn't non-free

**Comment by tonkku107** [comment]
Fixed
