### ISSUE TITLE
vote doesnt work

### ISSUE THREAD

**Issue by damiks4** [DiscordBotList/issues#910]
![image](https://github.com/top-gg/issues/assets/161946174/acf4ce7e-cfc2-435d-95c2-4f9d63c153f4)
i just cant vote. i dont know what to do. i tried voting like 3 weeks ago and i tried today too.

**Comment by marcorennmaus** [comment]
This repo has been retired. For support join our Discord server at https://discord.gg/dbl or reach out to support@top.gg.
