### ISSUE TITLE
Suggestion for Discord Server List Bot

### ISSUE THREAD

**Issue by Samcool236** [DiscordBotList/issues#94]
#### Suggestion

Make the *Discord Server List* Bot status invisible. This way, on support servers, for example, a 'miscellaneous' bot doesn't show, since the focus of a bot support server is for the bot that was made. 

On larger servers, it would hide the bot in the offline list.

#### Applicable Links or Attachments

N.A

**Comment by NotWeeb** [comment]
well the bot doesn't need to be shown at the top of the list for it to be able to work, but i'll take this into consideration
