### ISSUE TITLE
Voting bug

### ISSUE THREAD

**Issue by mrsheldon** [DiscordBotList/issues#96]
#### Expected Behavior

It says 24 and not 12

#### Observed Behavior

Change it to 12 hours

#### Applicable Links or Attachments

https://imgur.com/a/NmXbZ50

#### Steps to Reproduce

1. Open Discordbots.org
2. Go vote a bot
3. Try to vote to the same bot again after 1 minute

#### Web Browser and Version

Not relevant 

#### Operating System and Version

Not relevant 

#### Screen Resolution

Not relevant 

#### Additional Information/Comments

Cats are cute

**Comment by tonkku107** [comment]
Fixed
