### ISSUE TITLE
Spelling Error - Edit/add a bot's tags

### ISSUE THREAD

**Issue by tandpfun** [DiscordBotList/issues#99]
#### Expected Behavior

Correct Spelling:
Tags which best describe your bot (max. 6, games don't count)

#### Observed Behavior

Instead it was this spelling:
Tags which best describe your bot (max. 6, games dont count)

Fix "dont"

#### Applicable Links or Attachments

![screen shot 2018-07-23 at 8 07 09 pm](https://user-images.githubusercontent.com/28990589/43115050-eae32b68-8eb6-11e8-8263-4a2fe46ca96f.png)

#### Steps to Reproduce

1. Go to a bot you own
2. Edit the bot
3. The tag selection description has a spelling error

#### Web Browser and Version

Not Needed?

#### Operating System and Version

Not Needed?

#### Screen Resolution

Also Not Needed?

#### Additional Information/Comments

N/A

**Comment by Chewsterchew** [comment]
Grammatical error, spelling looks fine.

**Comment by Oliyy** [comment]
I've fixed this, it will be pushed live within the next week.
